/**
 * Created by wfq on 2015/7/21...
 */
var LNG = {
    UI_TITLE_YXXX: '英雄信息',
    UI_TITLE_DENGLU:'登  录',
    UI_TITLE_XUANZE: '请选择材料英雄',
    UI_TITLE_JINJIE: '进阶',
    UI_TITLE_YINGXIONG: '英雄',
    UI_TITLE_ZBXZ:'选择装备',
    UI_TITLE_DWXZ: "雕文选择",
    UI_TITLE_HDWP:'获得物品',
    UI_TITLE_SDJL: "扫荡奖励",
    UI_TITLE_ZBSJ:'升级',
    UI_TITLE_ZBTS:'请放入想要被吞噬的饰品',
    UI_TITLE_BEIBAO:'背包',
    UI_TITLE_TJP:'铁匠铺',
    UI_TITLE_XSRW:'悬赏任务',
    UI_TITLE_ZBQZ:'争霸强者',
    UI_TITLE_XZSP:'选择饰品',
    UI_TITLE_WYBQ: "成长指引",
    UI_TITLE_shipin_shengji:'请放入材料饰品',
    UI_TITLE_tanxian_kstx:'快速探险',
    UI_TITLE_tanxian_gjprize:'探险奖励',
    UI_TITLE_yingxiong_fenjie:'英雄分解',
    UI_TITLE_yingxiong_fight:'英雄出战',
    UI_TITLE_jingjichang_gjfight:'英雄出战',
    UI_TITLE_jingjichang_gjfight_defend:'防守阵容',
    UI_TITLE_jingjichang_fightreport:'战斗记录',
    UI_TITLE_jingjichang_gj_fightreport:'战斗记录',
    BTN_NAME_jingjichang_guanjunshilian:'冠军试炼',
    championtrial_defend_erro:'每支队伍需至少上阵一名英雄',
    UI_TITLE_damijing_setDef: "英雄备战",
    FIGHT:'开战',
    KLQ: "可领取",
    QUEDIN:'确定',
    TIAOZHAN:'挑战',
    TIRED: '您已累计在线2小时，请合理安排游戏时间。',
    XILA_SHUZI: ['', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'],
    QSRDHM: "请输入礼品码",
    GZXJC: "(贵族{1}加成)",

    ERROR_VERSION: '当前的客户端不是最新版本\n即将开始更新版本...',
    ajaxMaxError: '糟糕！您的网络状况似乎不是很好，请检查一下吧 ( >﹏<。)～<br><br>点击确定后将退出游戏重新登录',
    nexp: '经验',
    'NEXP': '经验',
    paynexp: '贵族经验',
    lv: '等级',
    'ji': '级',
    "WHGG_NAME": "维护公告",
    "WHGG": "亲爱的勇者大大们,当前服务器正在维护更新中,请稍作等待。",
    "JRQQ": "<br>详情请加入玩家群:<font color=#2bdf02>{1}</font>",
    'NOTRUNNING': '{1}正在维护中',
    "HDNEEDVIP": "贵族{1}及以上才可购买",
    "GETPRIZE": "领奖",
    QITA: '其他',
    BINGQIE:'并且',
    AND: '及',
    OR: '或',
    w:'万',
    zhongzu_1:'亡灵',
    zhongzu_2:'奥术',
    zhongzu_3:'邪能',
    zhongzu_4:'自然',
    zhongzu_5:'黑暗',
    zhongzu_6:'神圣',
    zhiye_1:'战士',
    zhiye_2:'法师',
    zhiye_3:'辅助',
    zhiye_4:'刺客',
    zhiye_5:'游侠',
    GHZX: "更换阵型",

    ZHONGZU_NEED:'属性激活限定：{1}',

    // 未开启相关
    OPEN_cclv : '需指挥中心达到{1}级',
    OPEN_lv : '{1}级开启当前功能',
    OPEN_vip:'需提升贵族到{1}级',
    'JZ_OPENLV': '玩家{1}级开放',
    'GN_OPENLV': '玩家{1}级开放{2}',
    WKQ_ZHUZHAN: '{1}级开启助战功能',
    WKQ_JIESUO: '<br><font color=#c80000>{1}阶解锁</font>',
    'reseted':'本轮活动已重置',
    network_api:'接口信息',
    network_noapi:'接口不能为空！',
    api:'接口',
    ERROR:'报错',
    args:'参数',
    ZHIHUAN:'置换',
    YGM: "已购买",
    YGMXJ: "已购买{1}件",
    SJ: "售价：<font node=1></font><font color=#30ff01>{1}</font>",
    JRKGMXC: "今日可购买<font color=#30ff01>{1}</font>次",
    YUAN: "元",
    DJDDXJ: "等级达到{1}级",
    LQ: "领取",
    YLQ: "已领取",
    YTH: "已弹劾",
    CYTH: "参与弹劾",
    DK: "打开",
    CKLQXQ: "查看领取详情",
    QXGMJJLB: "请先购买基金礼包",
    DJWDDYQ: "等级未达到要求",
    WDDLQTJ: "未达到领取条件",
    XGX: "剩余: {1}",
    YJ: "永久",
    HCZ: "后结束",
    LEIJI: "累积: {1}/{2}天",
    DQCZ: "当前充值{1}/{2}",
    LJCZ: "任意累计充值达到<font color=#ffb47d>{1}元</font>即可激活",
    XYKSY: "超值月卡剩余：<font color=#ffb47d>{1}天</font>",
    DYKSY: "至尊月卡剩余：<font color=#ffb47d>{1}天</font>",
    XYKSSY: "超值月卡剩余：",
    DYKSSY: "至尊月卡剩余：",
    CHOU: "抽",
    GXNSDXJ: "恭喜您升到<font color=#ff903f> {1} </font>级",
    SFGM: "确定购买当前商品?",
    QDGM: "确定购买？",
    SELLOVER: "商品已售空",
    HQYX: "获取英雄",
    HCCLBZ: "合成材料不足",
    DLJL: "{1}星英雄(整卡掉率{2}%，碎片掉率{3}%)",
    TXNDBG:"通关上一难度所有区域后解锁",
    DQSPYGM: "当前商品已购买",
    JHLB: "恭喜你激活了{1}星英雄养成礼包，是否前往购买？",
    xysd: "转盘商店",
    yxsd: "英雄商店",
    ghsd: "公会商店",
    yzsd: "远征商店",
    jjsd: "竞技商店",
    ywsd: "外域商店",
    sjssd: "召唤商店",
    ZH: "召唤",
    ZCTZ: "再次挑战",
    XZXTWXYX: "请选择相同的5星英雄",
    XZYXMX: "选择已获取的英雄为跨服玩法中展示的英雄形象",
    WZDSXX: "本服勇者，<font color=#ffc207>{1}</font>在第{2}届巅峰王者赛中取" +
        "的了<font color=#ffc207>{3}组{4}强</font>的成就，大家快来膜拜！",

    zonghe: '综合',
    xitong: '系统',
    ZWKFHXSL: "暂未开放后续征讨首领",
    'win': '胜利',
    'lose': '失败',
    siliao: '私聊',
    guoqi: '过期',
    NULL: '无',
    tian: '天',
    buzu: '不足',
    leijidenglu: '累计登录',
    mianfeilq: '免费领取',
    yuekalq: '特权领取',
    tq:'特权',
    jingri: '今日',
    mingri: '明日',
    shi: '时',
    'ci':'次',
    'pleasewait':'领主请{1}秒后再操作...',

    'loadingSvrlist': '正在读取区服列表 请稍候...',
    'choosesvrfirst': '请先选择服务器',
    'serverState1': '新服',
    'serverState2': '爆满',
    'serverState3': '维护',

    'COMING_SOON': '即将开放，敬请期待',
    'EXITGAME': '点击确定后将退出游戏进入挂机状态<br><br>小提示：挂机状态不耗流量不耗电',
    'RECONNSVR': '正在重新连接服务器...',
    GYTJRW: "官员以上玩家方可提交任务",
    GYKQZT: "官员以上玩家方可开启征讨",
    GHRW_BGBZ: "补给不足，无法开启",
    GHRW_ZTBS: "正在征讨首领中",
    GXBD: "贡献榜单",

    1: '一',
    2: '二',
    3: '三',
    4: '四',
    5: '五',
    6: '六',
    7: '七',
    8: '八',
    9: '九',
    10: '十',
    'ri': '日',
    RANK: '第{1}名',
    a: '甲',
    b: '乙',
    c: '丙',
    d: '丁',
    zhu: '组',
    D_X_PAGE:'第{1}章',
    D_X_YE:'第{1}页',
    GONGHUI_NAME:'公会名称',
    RENSHU:'人数',
    'BTN_OK': '确  定',
    'BTN_CANCEL': '取 消',
    'BTN_SY': '使 用',
    'BTN_HQ': '获 取',
    BTN_GM: '购 买',
    BTN_YGM: '已购买',
    BTN_LQ: '领 取',
    BTN_BKLQ: '不可领取',
    BTN_KLQ: '可领取',
    BTN_LQJL: '领取奖励',
    BTN_LQFJ: '领取附件',
    BTN_YLQ: '已领取',
    BTN_WTG: '未通关',
    BTN_CZ: '充 值',
    BTN_TZ:'挑  战',
    BTN_HF:'回  放',
    BTN_QW:'前  往',
    BTN_YSQ:'已售罄',
    WSB: "未上榜",
    ZWSP:'暂无商品',
    LIUCHANG:"流畅",
    TUIJIAN:"推荐",
    TISHI: '提示',
    QSRYXYHM: '请输入有效的用户名',
    NEED: '消耗{1}：',
    'XIAOHAO': '消耗',
    'GONGNENG': '功能',
    SDCG0: '解除锁定保护',
    SDCG1: '锁定保护成功',
    LQCG : '领取成功',
    'JIANGLI':'奖励',
    YULAN:'预览',
    CI: "次",
    TZCSBZ: "挑战次数不足",
    YDSZSL: "已达最大上阵数量",
    XYBBZ: "转盘币不足",
    GJXYBBZ: "超级转盘币不足",
    GMCG: "购买成功",
    RWZYZ: "存在未接取的紫色以上悬赏任务,确定刷新?",
    TSJSGH:'是否解散公会？',
    QBLQ: '全部领取',
    XYJ: '写邮件',
    SRSJRMC: '请输入收件人名称',
    SRYJNR: '请输入邮件内容',
    SRLTNR: '请输入聊天内容',
    SRFRIEND:'请输入玩家ID',
    SRSLWJM: '未选择私聊对象，无法发送',
    YJNRGC: '邮件内容过长',
    FSCG: '发送成功',
    fasong: '发送',
    QRSCHY: '确认删除好友吗?',
    NOHY: '对方并非你的好友,无法删除',
    FACE_ALERT: '最多只能输入20个表情',
    TEXT_ALERT: '最多只能输入40个字符',
    'YSZ': '已上阵',
    'SZ': '上阵',
    'CD': '穿戴',
    PVPING: '玩家对战中',
    ZW:'暂无',
    HY: "好友",
    KQXYC: "高级转盘需要45级或贵族等级3开启",
    Ci: "次",
    YYC: "(挑战{1}次)",
    WCJRRW: "完成今日日常任务后领取",
    RCRW: "日常任务",
    CJRW: "成就任务",
    GHJX: "公会捐献",
    GHFB: "公会副本",
    GHKJ: "公会技能",
    GHDT: "公会大厅",
    TGJL: "通关奖励",
    SCJL: "胜场奖励",
    YOUJIAN: "邮件",
    SXDBS: "搜寻到一个企图入侵公会的BOSS",
    XWYD: "虚位以待",
    DJC: "征讨首领第{1}层",
    SDXH: "收到鲜花达到{1}个",



    'load': '初始化中',
    'loadingbase': '基础资源{1}%',
    'loadConfig': '，此过程不消耗流量',
    'loadBeiBao': '，此过程不消耗流量',
    'loadBaowu': '，此过程不消耗流量',
    'loadZhuangBei': '，此过程不消耗流量',
    'loadShipin':'，此过程不消耗流量',
    'loadGlyph': "此过程不消耗流量",
    'loadBuiDui': '，此过程不消耗流量',
    'loadXiaobing': '，此过程不消耗流量',
    'loadQiji': '，此过程不消耗流量',
    'loadModule': '，此过程不消耗流量',
    'loadingRes': '，请稍后',
    'loadArmyList':'，此过程不消耗流量',

    'loadYingXiong': '，此过程不消耗流量',

    'loading': '等待',
    'liaotian': '聊天',
    'youjian': '邮件',
    "chakan": "查看",
    // 'zhuangbei':'军备',
    // 'shichang':'交易行',
    'jingjichang':'竞技场',
    // 'beibao':'背包',
    // 'huishou':'回收',
    // 'meiriqiandao':'每日签到',
    "showPrizeTxt": "查看奖励",

    'TS': '提示',
    'SY': '使 用',
    'FJ': '分解',
    '1C': '1次',
    '10C': '10次',
    '5C': '5次',
    'HC': '合成',
    'HS': '回收',
    'QB': '全部',
    'CS': '出售',
    'JD': '鉴定',
    'CKCC': '查看产出',
    'BAI': '百',
    'WAN': '万',
    'YI': '亿',
    'ZUIER': '罪恶',
    'ZUAN': '黄金',
    BTN_CHUSHOU:'出 售',
    BTN_SHIYONG:'使 用',
    BTN_HECHENG:'合 成',
    BTN_XIANGQING:'详 情',
    SHIYONG:'使用',
    CHUSHOU:'出售',
    HSXC: "还剩{1}次",
    GHTB: "公会探宝",

    'JINBI': '金币',
    'jinbi': '金币',
    // 'ZUANSHI': '黄金',
    // 'zuanshi': '黄金',
    'RMBMONEY': '黄金',
    'rmbmoney': '黄金',
    'SHUIJING': '水晶',
    'shuijing': '水晶',
    'DIANNENG': '电能',
    'dianneng': '电能',
    'GANGTIE': '钢铁',
    'gangtie': '钢铁',
    'SHIYOU': '石油',
    'shiyou': '石油',

    'GONGXIAN': '贡献',
    'JINGLIAN':'配饰精华',
    SHUAXIN:'刷新',
    ZSBZWFBL: "钻石不足，无法补领奖励",
    TJRWCG: "提交任务成功，公会补给+",
    KQZTSLCG: "开启第{1}层征讨首领成功",

    'XUEXI': '学习',
    'SHENGJI': '强 化',
    'PEIYANG': '培养',
    Max: '最高',
    'JIARU': '加入',
    'SUCCESS': '成功',
    SHEZHI:'设置',
    DELETE: '删除',
    ZSBZQWCZ: "您的钻石不足，是否前往充值",
    'DIUQI': '丢弃',
    'NAME_TIP': '请取一个霸气的名字吧',
    'WANJIA_NAME': '玩家名字:{1}',
    'NAME_MAX': '名字超出最大长度（最大{1}个字），请重新输入',
    'NAME_REG': '该角色名非法',
    'ZHANLI': '战力',
    'XXXX': '详细信息',
    'TOMAXLV': '已达到最高等级',
    'HUODE': '获得',
    'NUM': '数量',
    'UPDATE_ERROR': '更新失败',
    'JIHUO': '激活',
    'KAIQI':'开启',
    "DQYX": "当前英雄",
    DI_X_PAGE:'第{1}/{2}页',
    HECHENG:'合成',
    WUFAHECHENG:'无法合成',
    YXLBYM: "英雄列表已满，可通过提升贵族等级或购买增加英雄携带数量，是否前往购买？",
    HFZSBL: "是否确定花费{1}钻石补领当前关卡奖励？",
    ZSXX: "确定使用当前英雄作为你的展示形象？",
    QXBM: "取消自动报名？",
    'CURDJ': '当前等级：{1}',
    'NEXTDJ': '下一等级：{1}',
    'GONGHUI_NUM_RENSHU':'军团人数上限：{1}',
    'GONGHUI_NUM_ZJ':'专精上限：{1}',
    'XUNZHAO': '寻找',
    'LUEDUO': '争夺',
    'MUCHANG': '木场',
    'JINKUANG': '金矿',
    'SHIKUANG': '石矿',
    'SHOUHUO': '收获',
    'SHURU':'输入',
    'BOSSSW':'BOSS已被击杀',
    'GH_KQTJ' : '击败前一个BOSS后开启',
    SWSZZR: "尚未设置竞技场防守阵容无法参战，是否前往设置？",

    "BUYBOSSNUM_2":"购买一次挑战次数消耗：<font node=1></font>{1}<br><br>当前为：贵族{2}<br>剩余购买挑战次数：{3}次<br><br><font size=19>*提高贵族等级可获得更多购买次数</font>",
    ZWJL:'暂无奖励',
    'YWZB_PK_ME':'不能挑战自己哦！',
    JLSDLQBX: "巨龙神殿第{1}领取宝箱",
    BXJL: "宝箱奖励",

    'YWZB_TALK1':[
        '我比你厉害1',
        '我比你厉害2',
        '我比你厉害3',
        '我比你厉害4',
        '我比你厉害5'
    ],

    'YWZB_TALK2':[
        '你比我厉害1',
        '你比我厉害2',
        '你比我厉害3',
        '你比我厉害4',
        '你比我厉害5'
    ],

    'YWZB_TALK_WIN':[
        '你真菜1',
        '你真菜2',
        '你真菜3',
        '你真菜4',
        '你真菜5'
    ],

    'YWZB_TALK_LOST':[
        '你厉害1',
        '你厉害2',
        '你厉害3',
        '你厉害4',
        '你厉害5'
    ],


    'ITEM_ATTR_hp': '生命',
    'ITEM_ATTR_atk': '攻击',
    'ITEM_ATTR_def': '防御',
    'ITEM_ATTR_jingzhunpro': '命中率',
    'ITEM_ATTR_gedangpro': '格挡率',
    'ITEM_ATTR_speed': '速度',
    'ITEM_ATTR_undpspro': '伤害减免',
    'ITEM_ATTR_dpspro': '伤害加成',
    'ITEM_ATTR_skilldpspro': '技能伤害增加',
    'ITEM_ATTR_baojipro': '暴击率',
    'ITEM_ATTR_baoshangpro': '暴击伤害增加',
    'ITEM_ATTR_miankongpro': '免控率',
    'ITEM_ATTR_pojiapro': '破防率',
    'ITEM_ATTR_pvpdpspro': "pvp伤害增加",
    'ITEM_ATTR_pvpundpspro': "pvp伤害减免",


    'ITEM_ATTR_1_dpspro': '伤害',
    'ITEM_ATTR_1_dpsdrop': '减伤',
    'ITEM_ATTR_mhppro': '生命加成',
    'ITEM_ATTR_atkpro': '攻击加成',
    'ITEM_ATTR_defpro': '防御加成',
    'ITEM_ATTR_speedpro': '速度加成',
    'ITEM_ATTR_speeddrop': '降低速度',
    'ITEM_ATTR_baoshang': '暴伤',
    'ITEM_ATTR_baoshangdrop': '降低暴伤',
    'ITEM_ATTR_dpsdrop': '伤害减免',
    'ITEM_ATTR_backhp': '生命恢复',

    'ITEM_ATTR_atkdrop': '降低攻击',
    'ITEM_ATTR_dps': '伤害',
    // 'ITEM_ATTR_mhp': '生命',
    'ITEM_ATTR_mhpdrop': '降低生命',
    'ITEM_ATTR_mindps': '最小伤害',
    'ITEM_ATTR_maxdps': '最大伤害',
    'ITEM_ATTR_miss': '闪避',
    'ITEM_ATTR_misspro': '闪避率',
    'ITEM_ATTR_missdrop': '降低闪避',
    'ITEM_ATTR_mingzhong': '命中',
    'ITEM_ATTR_mingzhongpro': '命中率',
    'ITEM_ATTR_mingzhongdrop': '降低命中',
    'ITEM_ATTR_xixue': '窃取生命',
    'ITEM_ATTR_xixuedrop': '降低吸血',
    'ITEM_ATTR_backdps': '反伤',
    'ITEM_ATTR_defdrop': '降低防御',
    'ITEM_ATTR_power': '力量',
    'ITEM_ATTR_knowledge': '知识',
    'ITEM_ATTR_maxmp': '魔法值',
    'ITEM_ATTR_lucky': '暴击',
    'ITEM_ATTR_luckypro': '暴击加成',
    'ITEM_ATTR_luckydrop': '降低暴击',
    'ITEM_ATTR_mor': '追击',
    "ITEM_ATTR_backmp": "每回合回复魔法",
    'ITEM_ATTR_longdpspro': '麾下士兵远程伤害提升',
    'ITEM_ATTR_neardpspro': '麾下士兵近战伤害提升',
    'ITEM_ATTR_phydpspro': '麾下士兵物理伤害提升',
    'ITEM_ATTR_magdpspro': '麾下士兵魔法伤害提升',
    'ITEM_ATTR_earthdpspro': '英雄地系魔法攻击伤害提升',
    'ITEM_ATTR_firedpspro': '英雄火系魔法攻击伤害提升',
    'ITEM_ATTR_waterdpspro': '英雄水系魔法攻击伤害提升',
    'ITEM_ATTR_winddpspro': '英雄风系魔法攻击伤害提升',
    'ITEM_ATTR_jinbipro': '现金产量提升',
    'ITEM_ATTR_mucaipro': '电能产量提升',
    'ITEM_ATTR_kuangshipro': '钢铁产量提升',
    'ITEM_ATTR_exppro': '经验获得提升',
    'ITEM_ATTR_tips_atk': '[敌人0防御时，提升所有兵种{1}%的伤害]',
    'ITEM_ATTR_tips_def': '[受到{1}级敌人攻击时，所有兵种伤害降低{2}%]',
    'ITEM_ATTR_tips_power': '[敌人0知识时，提升英雄魔法{1}%的伤害]',
    'ITEM_ATTR_tips_knowledge': '[知识越高，兵种被英雄攻击时受到的伤害越低]',
    'ITEM_ATTR_tips_lucky': '[兵种幸运值越高，兵种幸运伤害触发几率越大]',
    'ITEM_ATTR_tips_mor': '[兵种士气值越高，多次行动几率越高]',

    'ITEM_ATTR_MHP': '生命加成',

    'ITEM_ATTR_firedpsdrop': 0,
    'ITEM_ATTR_neardpsdrop': 0,
    'ITEM_ATTR_winddpsdrop': 0,
    'ITEM_ATTR_waterdpsdrop': 0,
    'ITEM_ATTR_magdpsdrop': 0,
    'ITEM_ATTR_earthdpsdrop': 0,
    'ITEM_ATTR_longdpsdrop': 0,
    'ITEM_ATTR_gedang': 0,
    'ITEM_ATTR_ducontrol': 0,
    'ITEM_ATTR_phydpsdrop': 0,
    'ITEM_ATTR_dikangli': 0,

    HCCG: '合成成功',
    QHCG: '强化成功',
    SJCG: '升级成功',
    QHDJ: '强化等级',
    JJCG: '进阶成功',
    SXCG: '升星成功',
    XLCG: "洗练成功",
    CZCG: "重铸成功",
    TSCG: "吞噬成功",
    CZHSPZ: "当前精炼雕文存在红色品质雕文，确定精炼？",

    GHCG: '更换成功',
    JIE: "赛季",

    MFCS: '免费次数',
    BCMF: '本次免费',
    BCMFQWCG: "本次翻牌免费，请勿错过！",
    MF: '免费',
    MFSX: '免费刷新',
    EWSX: '额外刷新',
    BCBJ: '本次半价',
    BJCS: '剩余半价次数：',
    ZBCLBZ: "装备材料不足",
    SLBZ: "数量不足",
    'JIHUOLE':'激活了',
    'ZUHE':'组合',
    BTN_SX:'刷新',
    HJXX: "     {1}    <font color=#edbb82>获得</font>   <font color={2}>{3}</font>   <font color=#f6ebcd>{4}</font>",
    SETTING_INPUT:'请写上您的建议或者意见',
    FIGHT_NO_ZF:'未激活种族光环',

    SYSJ: '剩余时间：',
    SL: '数量：{1}/{2}',
    YJH:'已激活',
    WJH:'未激活',

    SX: '刷新',
    PM: '排名：{1}',
    HDEXP: '获得经验',
    SJEXP: '升级所需',
    YDC: '已达成',
    'YMJ':'已满级',
    'MJ':'满级',

    // 属性名相关
    dengji: '等级',
    ZBY: '装备于',
    X_LV_JS:'{1}级解锁',

    DW_1: "攻击型",
    DW_2: "生命型",
    DW_3: "平衡型",
    DIAOWEN: "雕文",
    sj: "升级",
    xl: "洗练",
    cz: "重铸",
    ts: "吞噬",
    DWCZNEED: "只有红色品质雕文才能重铸",
    DQDWMJ: "当前雕文已满级",
    DW_DJ: "等级：{1}",
    DW_DJJ: "等级：<font color=#1c9700>{1}</font>",
    DW_SX: "雕文属性加成：{1}%",
    DW_SXJ: "雕文属性加成：<font color=#1c9700>{1}%</font>",
    DWTIP: "存在未锁定的红色品质附加属性，是否确定继续洗练？",
    QFRZSYGDW: "请放入最少一个雕文",
    XIANGQIAN: "镶嵌",
    QD: "确定",
    QFRTSDDW: "请放入吞噬的雕文",
    QXZTSSX: "请选择吞噬属性",

    YXXX_DJSX:'等级上限提升：<font color=#1c9700>{1}</font>',
    YXXX_SXTS:'属性提升：<font color=#1c9700>{1}%</font>',
    YXXX_DWCC: "雕文插槽：<font color=#1c9700>{1}</font>",
    YXXX_DQSX: "当前属性提升：{1}%",
    YXXX_DQDJ: "当前等级上限：{1}",
    YXXX_DQDW: "雕文插槽：{1}",
    TY: "统御 ",
    ZWDW: "暂无段位",
    DQYXWJH: "当前英雄未激活",
    SZXJ: "升至{1}级可获得:",
    SJTJ: "升级条件：英雄最高星级达到{1}星",
    TMD: "天命点",
    QU: "区",
    WDQF: "我的区服",
    QTGJ: "全体攻击",
    QTSM: "全体生命",
    HDZSTX: "获得专属头像：",
    YXRH_MAN_ATK:"攻击融魂已达当前上限",
    YXRH_MAN_HP:"生命融魂已达当前上限",
    YXRH_TP1:'该英雄达到融魂上限<br><font color=#ff6400>六星</font>英雄可突破获得更高融魂上限',
    YXRH_TP2:'当前融魂进度已达到上限<br>突破需求英雄等级达到<font color=#46af08>{1}</font>',
    YXRH_TP3:'当前融魂进度已达到上限<br>突破需求英等级达到<font color=#ff6400>{1}</font><br>前往{2}提高等级上限',
    YXRH_TP4:'该英雄达到融魂上限<br><font color=#ff6400>十星</font>英雄可突破获得更高融魂上限',
    YXRH_TP5:'该英雄已达到融魂最高上限',
    YXRH_XQ1:"融魂等阶{1}阶激活({2}级可升阶)",
    YXRH_XQ2:"攻击上限：{1}",
    YXRH_XQ3:"生命上限：{1}",
    YXRH_XQ4:"额外属性加成：{1}+{2}",
    YXXX_YXSX:'英雄升星',
    TANXIAN_KSTX_1:'快速探险可获得120分钟的探险收益',
    TANXIAN_KSTX_2:'今日剩余免费次数：<font color=#1c9700>{1}</font>',
    TANXIAN_KSTX_3:'今日剩余购买次数：{1}<br>本次购买需要钻石：{2} <font color=#be5e30>(拥有{3}钻石)</font>',
    TANXIAN_KSTX_4:'激活"探险者特权"每日可免费3次，最多购买{1}次快速探险',
    TQZTWJH: "<font color=#63584a>特权状态: 未激活</font>",
    TQYJH: "特权状态: 已激活(剩余{1}天)",
    GMTXTQ: "购买探险者礼包可获得额外快速探险次数,是否前往购买?",
    ZWKFJYX: "暂无可分解英雄",
    ZWKFJSXYX: "暂无可分解四星以下英雄",
    SYXT: "剩余：<font color=#2bdf02>{1}天</font>",
    SYXS: "剩余：<font node=1></font>",
    YX: "英雄",
    JY: "经验",
    JB: "金币",
    CAILIAO: "材料",
    FENGSHOU: "丰收",
    WUWEI: "无畏",
    SILIAN: "试炼",
    HDZWKQ: "活动暂未开启",
    XDJL: "下档奖励: ",
    jingzhun:"精准率",
    GG: "公告",
    ZWNR: "暂无内容",
    GHBK: "公会宝库",

    'ZUIER_intr': '',
    'SHUIJING_intr':'使用水晶可到商城中抽取各种稀有兵种，还可购买部分指定礼包哟。',
    'MUCAI_intr': '升级建筑的必需品之一，可通过贵族礼包、基地电能建筑及任务获取。',
    'KUANGSHI_intr': '升级建筑的必需品之一，可通过贵族礼包、基地钢铁建筑及任务获取。',
    'SHIYOU_intr': '升级建筑的必需品之一，可通过贵族礼包、基地石油建筑及任务获取。',
    'RONGYU_intr': '在竞技场中每天都能获得大量荣誉，用它荣誉商店中可换到顶级军备及兵种。',
    'MOHUN_intr': '可到钨金商店中换取想要的兵种碎片，回收兵种可大量获取。',
    'JINGTI_intr': '回收军备的产物，可在军备商店中重新制作为全新的军备或强化石。',
    'FANRONGDU_intr': '军团发展的基础资源，可通过玩家各种日常行为增加。',
    'FWJINGHUA_intr': '锻造符文中产生的符文精华，可在符文商店中购买指定的任意符文。',
    'BWJINGHUA_intr': '精炼配饰中产生的配饰精华，可在配饰商店中购买指定的极品配饰。',
    JUNGONG_intr:'跨服争霸中奋勇杀敌获得的功勋，强者的证明。',
    JIFEN_intr:'跨服积分赛积分，用于评价本次跨服积分赛排名',
    XINGCHENJIFEN_intr:'军团战星辰积分，用于评价本次跨服军团战的个人与军团排名。',
    payexp_intr:'硬通货，这个东西的作用就不言而喻了......',
    shenyin_intr:'在神殿争夺战中居功至伟的证明，可在神印商店中兑换珍奇道具！',
    ghmoney_intr:'军团资源之一，用于军团升级，可在军团建设与军团任务中获得。',
    ghgongxian_intr:'军图资源之一，用于军团科技和军团商店，可在军团副本、军团建设与军团任务中获得。',
    ghboom_intr:'军团资源之一，用于军团升级，可在军团副本、军团建设、军团任务和竞技场等玩法中获得。',
    CSH: "初始化中，请稍候",

    KFZ_ZB_tip:'战前准备阶段，快去提升自己一下吧！',
    KFZ_ZB:'争霸赛',
    KFZ_JF:'积分赛',
    KFZ_tip_1:'距离{1}开始：',
    KFZ_tip_2:'距离{1}结束：',
    KFZ_JF_refreshEnemy:'是否花费<font color=#00ff0c>20</font>钻石刷新挑战对手？',
    KFGHZ_refreshEnemy:'是否花费<font color=#00ff0c>30</font>钻石刷新挑战对手？',
    BEGAN_TIME:'开始时间：',
    END_TIME:'结束时间',
    YJS:'已结束',
    JJC_JF_SC_tip:'挑战达到{1}次<font color={3}>{2}</font>',
    KFZ_JF_SC_tip:'胜场达到{1}次({2})',
    KFZ_ZB_RZ_1:'{1}被{2}挑战，<font color=#eb3a3a>战斗失败了</font>，排名下降至<font color=#eb3a3a>{3}</font>名。',
    KFZ_ZB_RZ_1_1:'{1}被{2}挑战，<font color=#eb3a3a>战斗失败了</font>，排名不变。',
    KFZ_ZB_RZ_2:'{1}被{2}挑战，<font color=#30ff01>战斗胜利了</font>，排名不变。',
    KFZ_ZB_RZ_3:'{1}向{2}发起了挑战，<font color=#eb3a3a>战斗失败了</font>，排名不变。',
    KFZ_ZB_RZ_4:'{1}向{2}发起了挑战，<font color=#30ff01>战斗胜利了</font>，排名上升至<font color=#30ff01>{3}</font>名。',
    KFZ_ADD_TIP:'积分赛已结束，不可购买次数',
    KFGHZ_TZ10_TIP:'剩余挑战次数不足10次',
    KFGHZ_TZ10_TIP2:'花费{1}钻石随机挑战{2}名对手（胜率100%），获得{3}星辰积分',
    KFGHZ_SJCW:'数据错误',
    KFZ_ZB_REF_TIP:'刷新次数已用完',
    KFZ_JF_SL:'已战胜当前对手',
    KFZ_JF_SB:'已被当前对手击败',
    KFZ_RANK_jifen:'每周五 23:00后可领取奖励！',
    KFZ_RANK_zhengba:'每周日 22:00后可领取奖励！',
    KFZ_PMJL:'积分排名',
    KFZ_SJJL:'奖励预览',
    KFZ_ZB_PHB:'奖励预览',

    HUODONG_HD_OVER:'该活动已结束',
    HUODONG_CZJJ_YUEKA:'至尊月卡用户才可购买超级基金，你尚未购买，是否前去购买？',
    HUODONG_CZJJ_ZHIZUNKA:'至尊月卡用户才可购买超级基金，你尚未购买，是否前去购买？',
    HUODONG_CZJJ_JLYLQ:'活动奖励已领完',
    HUODONG_YJJ_LJ:'当前累计：{1}天',
    HUODONG_YJJ_LQSJ:'领取时间：{1}\n(每天登录累计1天, 最大30天)',

    TX_NEED_JS:'请通关上一关卡',
    NEED_X_LV:'需要等级达到{1}级',
    BTN_KSTX:'快速探险',
    SHOP_ITEM_OVER:'该商品已售罄',
    SHOP_NEED_BUY:'确定要购买该商品么？',
    HBBZ: "货币不足",
    YC:"一次",
    SC:"十次",
    JLYL: "奖励预览",
    JLYL_INFO: "活动最后一天23:55分结算排行奖励",
    JLCK:'奖励查看',
    QTGSYGQ: "请通关上一关卡",
    SZYXBZ: "上阵英雄不足",
    YINGXIONG_BUG_CELL:'花费{1}钻石购买{2}个英雄携带数量上限？',
    GMSLCS: "本次购买将花费 <font node=1></font><font color=#78ff2f>{1}</font>,是否购买？<br>今日剩余购买次数：<font node=2></font>",
    CHUANSHANG:'穿上',
    XIEXIA:'卸下',
    YH: "以后",
    HUOBI1: "灵魂石",
    HUOBI3: "远征军声望",
    HUOBI2: "转盘积分",
    HUOBI5: "公会贡献",
    HUOBI4: "荣誉点",
    BZ: "帮助",
    FSJJ: "巨龙结晶",
    BUZU: "不足",
    CSBZ: "次数不足",
    TSVIP: "提升贵族等级可以获得更多购买次数",
    FXQJCNLQ: "返现期间才能领取",
    JZDQGFX: "截止当前共返现{1}钻石！",
    DJBZKQ: "等级不足,{1}级开启",
    SDJKQ: "{1}{2}级开启",
    SJDL: "随机掉落{1}",
    ZHUANGBEI_TYPE:'类型: ',
    ZHUANGBEI_TYPE_1:'武器',
    ZHUANGBEI_TYPE_2:'戒指',
    ZHUANGBEI_TYPE_3:'头盔',
    ZHUANGBEI_TYPE_4:'胸甲',
    ZHUANGBEI_TYPE_5:'饰品',
    ZHUANGBEI_TYPE_6:'宝石',
    ZWKZHYX: "暂无可置换4-5星英雄",
    BTN_TUOXIA:'卸 装',
    BTN_TIHUAN:'更 换',
    TIHUAN:'替换',
    BTN_CHUANSHANG:'穿 上',
    BTN_ZHUANHUAN:'转 换',
    BTN_SHENGJI:'强 化',
    KJS:'可解锁',
    BAOSHI:'宝石',
    ZHUANHUAN:'转 换',
    SHIPIN:'饰品',
    DAOJU_TYPE_item:'道具',
    DAOJU_TYPE_equip:'装备',
    DAOJU_TYPE_shipin:'饰品',
    DAOJU_TYPE_baoshi:'宝石',
    DAOJU_TYPE_attr:'货币',
    DAOJU_TYPE_hero:'英雄',
    BTN_ADD1:'加入1个',
    BTN_ADD10:'加入10个',
    YINGXIONG_SHIPIN_SX_BUZU:'升星所需的材料不足',
    YINGXIONG_UP_MAX:'恭喜你将{1}升满',
    UI_TITLE_yingxiong_jianjie:'英雄信息',
    GOUMAI:'购买',
    YX_FENJIE_TIP_2:'分解英雄中包含{1}星英雄，确定分解？',
    YX_FENJIE_TIP_1:'请放入需要分解的英雄',
    FENJIE:'分解',
    YX_FENJIE_TIP3:'英雄分解会返还所有培养材料',
    YX_FENJIE_TIP4: "请放入需要分解的英雄",
    TANXIAN_TG_NAME:'通关第{1}关卡',
    TANXIAN_TG_CENG:'通关第{1}层',
    DDCENG: "本轮手动挑战{1}层关卡 ({2}/{3})",
    FST_TADQ_CENG:'巨龙神殿第{1}层领取宝箱',
    TANXIAN_TADQ_CENG:'通关第{1}层 ({2}/{3})',
    TANXIAN_TXDQ_CENG:'通关第{1}关卡 ({2}/{3})',
    TANXIAN_CENG:'第{1}层',
    ZJ: "赞：{1}",
    QXTGDQZJ: "请先通关当前章节",
    PLCG: "评论成功",
    VANDDJ: "VIP2或60级以上才能评论",
    GUAJI:'挂机',
    BAOCUN:'保存',
    QFRXYBZDYX: "请放入需要备战的英雄",
    YX_FIGHT_TIP_1:'请放入需要出战的英雄',
    YX_FIGHT_TIP_2:'每队至少上阵一个英雄',
    WORLDTREE_TIP_1:'你还有置换的英雄未保存，确定要离开么？',
    YINGXIONG_ZHENFA_TIP_1:'上阵英雄均享受以下光环属性',
    X_ROUND:'第<font color=#fff71d>{1}</font>回合',
    JFCGSX: "当前已有{1}/{2}悬赏积分，领取后超出上限部分将损失，确定领取？",
    JFCGSX_liuzhecankaoyong: "当前已有{1}/{2}悬赏积分,领取{3}悬赏积分后,超出上限部分将损失，是否确定领取?",
    XTGLY: "系统管理员",
    GHHZ: "公会会长",
    YPB: "已拉黑",
    PHB: "排行榜",
    GHPHB: '公会排行',
    QSRZQDSZ: "请输入正确的数值",
    JSGH: "解散后所有公会成员将做退会处理，是否确定解散？",

    GONGHUI_ONLY_HZ:'仅公会会长可以操作',
    LIEBAO:'列表',
    CHUANGJIAN:'创建',
    SHENQING:'申请',
    GONGHUI_MAX_APPLY_NUM:'申请公会数量已满',
    UI_TITLE_gonghui_selectflag:'选择公会旗帜',
    UI_TITLE_gonghui_paihangbang:'公会排行',
    GONGHUI_POWER_0:'会长',
    GONGHUI_POWER_1:'官员',
    GONGHUI_POWER_2:'成员',
    GONGHUI_POWER_3:'成员',
    ZAIXIAN:'在线',
    TUICHU:'退出',
    JBSL: "击败前一层首领，并领取宝箱奖励解锁",
    GONGHUI_TIP_1:'会长不可以退出公会',
    UI_TITLE_gonghui_dating_applylist:'申请列表',
    GONGHUI_TIP_2:'您是否确定退出该公会？',
    CAOZUO:'操作',
    ZHAOMU:'招募',
    GONGGAO: "公告",
    XGGG: "修改公告",
    TJCG: "添加成功",
    SCCG: "删除成功",
    QSRNR: "请输入内容",
    ZHAOMU_INFO:'请输入招募信息',
    ZHAOMU_CONTENT:'欢迎加入公会，大家积极捐献，一起打公会副本，公会宝库还可领取宝箱哦！',
    GHMRNR: "欢迎加入公会，大家积极捐献，一起打公会副本，公会宝库还可领取宝箱哦！",
    NEED_GH_INTR:'请输入公会简介',
    FASONG:'发送',
    XIUGAI:'修改',
    MINGZI:'名字',
    FXJSSJ: "返现结束时间",
    WDFXSJ: "未到返现时间",
    HDLJSJ: "距离活动领奖",
    LJJSSJ: "领奖结束时间",
    FXYLQ: "返现已领取",
    GONGHUI_NAME_INFO:'请输入公会名字',
    GONGHUI_NAME_TIP:'新的公会名',
    RENMING:'任命',
    GONGHUI_RENMING_X:'您确定将{1}任命为{2}吗？',
    GONGHUI_QINGLI_X:'您确定将{1}请离公会吗？',
    GONGHUI_FUBEN_TIP1:'请先通关前置关卡',
    GONGHUI_TANHE:'你确认发起会长弹劾吗？发起后24小时内，公会内所有玩家均可争夺会长之位。',
    UI_TITLE_SHPH:'伤害排行',
    SDSW: "神殿守卫 {1}",
    FBSL: "副本首领",
    BTN_ZD:'战斗',
    BTN_FH:'复活',
    GONGHUI_FUBEN_FIGHT_MAX:'已达最大挑战次数，请明天再试',
    CHONGZHI:'结束',
    ZHCG: "置换成功",
    HDYJS: "活动已结束",
    JIESU: "重置",
    NI:"你",
    CUR_LV:'当前等级',
    MAX_LV:'已达最高',
    ZENGJIA:'增加',
    UI_TITLE_player_changhead:'头像列表',
    PLAYER_NAME_INFO:'请输入你想修改的名字',
    PLAYER_NAME_TIP:'2-6个汉字',
    YXRY: "活动期间{1}达到{2}星可领取",

    ZHENXING: '阵型',
    WZRY_ZZS: '钻石赛',
    WZRY_WZS: '王者赛',
    WZRY_ZZS_FZ: '你入围了钻石赛{1}组，请进入查看自己的比赛详情',
    WZRY_ZZS_WFZ: '你没有入围钻石赛，但你可以观看钻石赛的比赛',
    WZRY_JSWKQ: '决赛将在分组赛结束后开启',
    WZRY_JSKQ: '决赛开启',
    WZRY_LOG3: '钻石赛战斗日志',
    WZRY_LOG5: '王者赛战斗日志',
    WZRY_GUESS: '贵族等级不足，无法进行本档竞猜',
    WZRY_GUESS_SUCC: '竞猜成功',
    WZRY_MAIN_tip_1: '{1}级以上玩家可参与本周大乱斗活动，若报名人数大于256人，则活动将在周二0点开启，报名后立刻获得<font color=#fff00>雕文精华</font>500个',
    BAOMING: '报名',
    ITEM_FENJIE_TIP_1: '确定要分解全部的宝物箱吗？',
    BKSDSYSXXL: "不可锁定所有属性进行洗练",
    WBM: '未报名',
    YBM: "已报名",
    LKBM: '立刻报名',
    WZRY_MAIN_HD_NOOPEN: '活动暂未开启',
    WZRY_MAIN_DLD_NOBM: '未报名无法参与，请周三后观看钻石赛',
    X_rank: '{1}名以后',
    WZRY_BM_TIP_1:'等级不足{1}级无法自动报名',
    WZRY_BM_TIP_2:'贵族等级不足',
    WZRY_RYJL_1: '大乱斗积分达到奖励需求将自动通过邮件发送奖励',
    WZRY_RYJL_2: '奖励将在钻石赛结束通过邮件发放',
    WZRY_RYJL_3: '奖励将在王者赛结束通过邮件发放',
    WZRY_DLD_refresh: '正在刷新对手，请稍等。。。',
    WZRY_RYZD_tip_1: '荣耀之巅的史册 等着您来开启',
    WZRY_RYZD_X_RANK: '第{1}期荣耀王者',
    WZRY_GHZX: '你可以将当前阵型保存为参与钻石赛或王者赛的专属阵型，每次保存阵型需要间隔10分钟。（每轮晋级赛开启时间的上下30分钟不可保存阵型）',
    WZRY_ZSS_ZU: '钻石赛{1}组',
    WZRY_DJC:'第{1}轮',
    BZTZSJ: "当前不在挑战时间内",
    WZRY_HUODONG_NOOPEN: '报名人数不足，活动未开启',
    WZRY_HUODONG_BAOMING: '等待各路英雄报名中，将在明日正式开赛',
    WZRY_DLD_JIFEN: '乱斗积分+{1}',
    WZRY_DLD_PH_JIFEN: '乱斗积分：{1}',
    WZRY_MAIN_ZX: '战斗期间不可更换阵型',
    WZRY_DDJS:'请耐心等待前置晋级赛结束',
    wangzherongyao_dld_ph: "乱斗排行",
    wangzherongyao_jcwz:"竞猜王者",
    GUIZU:"贵族{1}",
    DWCC: "雕文插槽：",
    ZWJS: "暂未开放",

    JOB_1:'战士',
    JOB_2:'法师',
    JOB_3:'辅助',
    JOB_4:'刺客',
    JOB_5:'游侠',
    GONGHUI_KEJI_OPEN:'需要上个技能达到10级',
    MIANFEI:'免费',
    GONGHUI_KEJI_TIP1:'重置公会技能将返还培养消耗的全部材料！',
    UI_TITLE_gonghui_fuben_prize:'战斗奖励',
    JISHA:'击杀',
    PER_FIGHT:'每次战斗',
    QTGQZGQ: "请通关前置关卡",
    OKCOLOR: "当前饰品为{1}品质,确定将其作为培养材料？",
    CCOLOR: "橙色",
    HCOLOR: "红色",
    BLSJYJS: "本轮赛季已结束",
    HD_ZCJB: "活动期间，每日消耗钻石的{1}%存入返利宝箱中，活动结束后根据VIP等级可领取<font color=#ffaf5a>钻石宝箱</font>(活动持续7天，第8天领奖)",

    TFRYXSL:'已放入英雄数量',
    VIPFL: "vip{1}可领取{2}%返利，总计<font node=1></font> x{3}",
    MBJL: "目标奖励",
    YX_SX_XZ_TIP_1:'选择材料英雄数量不足',
    YX_LOCKING:'该英雄已锁定',
    YX_YBXZ: "该英雄已被选择",
    YX_X_LOACKING:'该英雄处于{1}防守阵容中',
    YX_SX_XZ_FULL:'每次最多放入10个英雄',
    YX_FIGHT_XZ_FULL:'当前选择英雄已满',
    YX_YZW: "英雄已阵亡",
    CLFH:'材料返还',
    GL: "概率: {1}%",
    nuqi: "怒气",
    XSYDY: "新手引导员无阵容设置",
    DMJ_BJ: "当前补给暂无，有几率通关获得",
    dmj_syyj: "是否使用<font color=#fff71d>{1}</font>补给",
    JSDJS: "结束倒计时: ",
    JXTG: "极限通关",
    ALL_HERO_DEAD: "本轮活动已结束",
    TANXIAN_MAP_TIP_1:'当前区域尚未解锁，请通过前置关卡',
    TANXIAN_MAP_TIP2:'你确定要前往该区域进行战斗？',
    TANXIAN_MAP_TIP3: "已处在当前区域",
    NLTANDVIP: "能量条满且贵族3玩家方可召唤",
    ZSBZ: "钻石不足",
    YJBZ: "印记不足",
    SFKQTB: "是否确定开启团本",
    TS1: "一、祭祀规则：<br>1.召唤祭祀可以召唤1-5星英雄，幸运祭祀可以召唤2-5星英雄，先祖祭祀可以召唤3-5星英雄，传说祭祀必得5星星英雄。<br>2.每次召唤祭祀可得1个传说英雄碎片，幸运祭祀可得2个传说英雄碎片，先祖祭祀可得20个传说英雄碎片。<br>3.贵族3以上玩家可以解锁传说祭祀，每次传说祭祀需要消耗999个传说英雄碎片。<br>二、祭祀概率：<br>召唤祭祀：1星53%、2星36%、3星9.4%、4星1.5%、5星0.1%<br>幸运祭祀：2星35.5%、3星50%、4星13.5%、5星1%<br>先祖祭祀：3星78.5%、4星18%、5星3.5%<br>传说祭祀：5星100%",
    TS2: "每日试炼：<br>1.击败试炼守卫者可以获得大量英雄培养材料，每日不要错过哦！<br>2.贵族等级越高的玩家可以购买更多的挑战次数。<br>3.挑战试炼成功有概率获得多倍奖励。",
    TS3: "1.通过刷新可以刷出高品质的悬赏任务，任务品质越高奖励越丰厚！<br>2.英雄达成任务派遣条件，消耗一定数量悬赏积分即可接取任务。<br>3.每个任务需要进行一段时间，期间已派遣的英雄无法执行其他任务。<br>4.每天有2次免费刷新任务机会，也可以消耗悬赏刷新券或钻石刷新。",
    TS4: "一、魔法转盘：<br>1.消耗转盘币可以在普通转盘抽奖，消耗高级转盘币可以在高级转盘抽奖。<br>2.贵族2以上玩家消耗12个普通转盘币即可在普通转盘进行十五连抽。<br>3.每次在转盘抽奖都能获得转盘能量，转盘能量满后可以获得1次免费的幸运转盘抽奖。<br>4.普通转盘幸运转盘可以获得大量经验、金币；高级转盘幸运抽奖能获得稀有传说英雄。<br>5.每次在普通转盘抽奖都将获得转盘积分，转盘积分可以在转盘商店购买商品。<br>6.转盘商品每天0点时会自动刷新。",
    TS5: "一、召唤之书：<br>1.每张召唤卷可以从对应种族的召唤之书中召唤1次英雄<br>2.召唤将概率获得传说或史诗英雄的整卡和碎片<br>3.每次召唤必定获得1个张召唤卷残页和若干置换精华，一定数量的召唤卷残页可以用来兑换指定传说英雄。<br>二、英雄转换：<br>1.通过置换精华，可以将除开神圣和黑暗以外种族的4、5星英雄进行随机转换。<br>2.英雄转换后，新生的英雄将继承原有英雄的所有属性。",
    TS6: "1.毁灭巨龙的爪牙遍布了巨龙神殿，但同时他们也守护着丰厚的奖励<br>2.击败守卫可以获得勇气徽章，每挑战10层还能获得怪物守护的宝箱。",
    TS7: "1.远征每日0点刷新。<br>2.40级以上的英雄才能参加远征，战斗后敌我双方英雄的血量不恢复。<br>3.战斗获取的远征军声望可以在远征商店兑换强大的物品。<br>4.远征过程中可以获得宝箱奖励，宝箱中存放着补给品。<br>5.使用补给品可以恢复英雄生命、怒气甚至复活已经阵亡的英雄。",
    TS8: "TS8",
    TS9: "自由竞技场<br>1.自由竞技场每周1开启，周日结束，期间每天21点结算排名奖励，周日22点结算赛季奖励。<br>2.每次挑战竞技场可以获得翻牌奖励。<br>3.竞技场按照玩家积分排名，积分相同玩家按照战力排名。<br>冠军竞技场<br>1.冠军竞技场每周五开启，周日结算，周日22点结算赛季奖励，通过邮件发放。<br>2.每次挑战竞技场可以获得翻牌奖励。<br>3.竞技场按照玩家积分排名，积分相同玩家按照战力排名。<br>4.冠军竞技场需要玩家设置3队英雄，与敌人布置的3队英雄依次战斗！",
    TS10: "1.公会成员每天可通过公会捐献来增加公会经验，提升公会的等级。<br>2.公会每升级2级，成员上限增加1个，公会最多容纳40人。<br>3.玩家退出公会后会扣除最近3天为公会增加的公会经验。<br>4.会长超过3天未上线，则可对会长发起弹劾。弹劾期为1天，弹劾期会长上线会自动取消弹劾。<br>5.消耗公会贡献可以提升公会科技等级，升级对应职业的公会科技对所有等级2级及以上的当前职业英雄有效。",
    TS11: "1.公会副本一共12个章节，每个章节5个守关首领，击败后进入下一章。<br>2.每次挑战首领都能获得奖励，首领被击杀后，根据伤害排名发放排名奖励。<br>3.相同的首领同个玩家只有首杀时能获得奖励（更换公会重复击杀无效）<br>4.若更换到副本进度较高的公会导致部分首领无法挑战，则可以选择花费钻石补领对应关卡的奖励。（补领的奖励为21-50名的挑战者对应的奖励档位，且补领成功后将视为对应关卡的首领已挑战）",
    TS12: "1.每日登录即可领取奖励。<br>2.领取完30次后奖励内容刷新，重新开始领取。",
    TS13: "公会探宝<br>1、公会所有成员都可以探宝搜寻奖励，并有一定概率搜寻到怪物。<br>2、怪物守卫着大量钻石，击败怪物可以获得奖励。<br>3、好友或公会成员可以相互帮助击杀怪物。<br>4、挑战怪物可以获得贡献积分，击杀者还能获得额外钻石奖励。<br>5、每周根据贡献积分，会结算一次贡献排名奖励。",
    TS14: "英雄分解<br>1、游戏初期赠送的大部分英雄都可以用于融合祭坛合成第一个5星寒冰女巫，请勿随意分解。<br>2、英雄进行分解可以得到一定的灵魂石和其他培养材料。<br>3、英雄分解将返还全部将返还培养消耗的所有升级材料、进阶材料、宝石材料。",
    TS15: "融合祭坛<br>1、融合祭坛可以将同名低星英雄合成高星英雄。<br>2、合成成功后的英雄将继承主英雄的等级和进阶等级。<br>3、合成成功后，作为辅助材料的英雄将返还培养消耗的所有升级材料、进阶材料、宝石材料、饰品和装备。<br>4、5星英雄 = 同名4星主英雄*1 + 同名4星辅英雄*2 + 同种族任意4星英雄*5 + 同种族任意3星英雄4个。<br>5、6星英雄 = 同名5星主英雄*1 + 同名5星辅英雄*1 + 同种族任意5星英雄*3 + 同种族指定5星英雄*1。",
    TS16: '<font color=#00FF0c>积分赛赛程介绍</font><br>1、比赛阶段<br><font color=#00FF0c>每周一00:00至周五23:00</font>是积分赛挑战时间，战胜不同的对手会获得<font color=#00FF0c>不同的</font>积分和军功奖励。<font color=#00FF0c>每日胜利场次达到目标也有军功奖励</font>。<br>休战阶段<br><font color=#00FF0c>每周五23:00至周日23:59</font>为积分赛休战阶段，在此期间可进入积分赛内<font color=#00FF0c>领取积分排名奖励</font>。<br>2、挑战规则<br>每天有<font color=#00FF0c>15次免费刷新次数</font>和<font color=#00FF0c>15次免费挑战次数</font>，免费刷新次数用完后<font color=#00FF0c>可使用钻石刷新对手</font>。<br>挑战对手次数也可用钻石购买，每日24点将重置挑战次数（提升贵族等级，可增加每日购买次数）。<br>3、积分赛<font color=#00FF0c>战胜对手</font>最高可获得积分*35，军功*18，最低可获得积分*30，军功*15，挑战失败则获得<font color=#00FF0c>一半</font>的积分和军功。<br>4、晋级规则<br>积分赛结束后，排行前300名的玩家获得参加当届争霸赛资格，同时<font color=#00FF0c>周五23:00每个区服竞技场前10名（等级达到50级或以上）或总积分达到4500分以上</font>也可获得参加当届争霸赛的资格。<br> <br><font color=#00FF0c>争霸赛赛程介绍</font><br>1、筹备阶段<br><font color=#00FF0c>每周五23:00至周六10:00</font>为争霸赛筹备阶段，此阶段争霸赛无法进入。每周五23:00积分赛排名前300的玩家和各区竞技场排名前10的玩家（等级达到50级或以上）将进入争霸赛。<br>分组阶段<br>争霸赛会将区服开区时间相近100名玩家分到同一组比赛。（最后不足100人的玩家将合并到前一组）<br>争霸阶段<br><font color=#00FF0c>每周六10:00至周日22:00</font>为争霸阶段，此阶段玩家可在<font color=#00FF0c>争霸赛挑战区</font>击败对手获得更高的名次，也可在<font color=#00FF0c>强者区</font>观摩大神的风采。<br>休战阶段<br><font color=#00FF0c>每周日22:00至下周五23:00</font>为争霸赛休战阶段，在此期间可进入争霸赛内<font color=#00FF0c>领取排名奖励</font>。<br>2、挑战规则<br>每天有<font color=#00FF0c>15次免费挑战次数</font>，挑战次数用完后可用钻石购买（贵族等级越高，每日可购买次数越多）。<br>3、奖励规则<br>争霸赛中战斗胜利可以获得50军功，失败可获得10军功。争霸赛结束后可根据争霸赛排名领取排行奖励。<br>4、争霸强者<br>争霸赛中前20名排名发生变化的战斗，将会以录像的形式储存在争霸强者中供大家参考学习，想一览大神的风采不要忘记来看看哟。',
    TS17: "1、公会所有成员可购买公会宝箱，每天购买上限为10次。<br>2.购买宝箱的成员可立即获得宝箱专属奖励。<br>3.成功购买宝箱会在公会宝库中出现一个公共宝箱，宝箱内有10分礼物供10名公会成员领取。<br>4、公共宝箱只会保存24小时，保存期限内未领取则过期。",
    TS18: "一、秘境规则：<br>1.守望者秘境是周期性活动，每两天1个周期，每期活动，玩家需要选择6名英雄挑战秘境。<br>2.秘境一共有600层，每次击败守层怪物可进入下一层秘境。<br>3.每层战斗结束后己方英雄和敌方怪物的血量及能量都会保存，已阵亡的英雄无法再参与战斗。<br>4.每期活动重新开启时，玩家将自动快速挑战到历史最大层数减30层的关卡。<br>5.每期活动当己方所有英雄全部阵亡，本轮秘境挑战结束。<br>二、秘境奖励：<br>1.“目标奖励”每期活动手动挑战的关卡到到30层将获得大量融魂材料目标奖励。<br>2.“合剂”击败守关怪物后，获得随机合剂效果，全体出战英雄在本次活动中属性获得提升。<br>3.“掉落奖励”击败守关怪物后随机掉落1份道具奖励。<br>4.“地精商品”击败守关怪物后，出现地精商人，商人随机出售一件商品。<br>5.“补给品”击败守关怪物后，出现随机补给品，可以恢复英雄属性、召唤稀有商人甚至直接毒杀BOSS。<br>6.“翻牌奖励”击败守关怪物后，出现翻牌事件，抽取大量奖励！",
    TS21: "一、统御<br>1.所有可升至6星的英雄均能进行统御培养。<br>2.提升英雄的统御等级需消耗指定类型的英雄和金币。<br>3.每次培养任意英雄统御等级都能获得天命值。<br>4.当天命值累计到一定程度后可触发对应天命称号的属性加成。<br>5.天命称号达到一定等级可激活专属头像。<br>6.每天可领取对应天命称号的日常英雄经验奖励。",
    TS19: "一、统御<br>1.所有可升至6星的英雄均能进行统御培养。<br>2.提升英雄的统御等级需消耗指定类型的英雄和金币。<br>3.每次培养任意英雄统御等级都能获得天命值。<br>4.当天命值累计到一定程度后可触发对应天命称号的属性加成。<br>5.天命称号达到一定等级可激活专属头像。<br>6.每天可领取对应天命称号的日常英雄经验奖励。",
    TS20: "一、统御<br>1.所有可升至6星的英雄均能进行统御培养。<br>2.提升英雄的统御等级需消耗指定类型的英雄和金币。<br>3.每次培养任意英雄统御等级都能获得天命值。<br>4.当天命值累计到一定程度后可触发对应天命称号的属性加成。<br>5.天命称号达到一定等级可激活专属头像。<br>6.每天可领取对应天命称号的日常英雄经验奖励。",
    TS23: "跨服公会争锋赛程介绍<br>一、休赛期流程<br>1、每<font color=#00FF0c>周日00:00-24:00</font>为跨服争锋休赛期，此时可以<font color=#00FF0c>报名下个赛季比赛</font>。<br>2、报名需要公会中有10名以上玩家达到30级；报名成功后公会中30级及以上的玩家均可参与公会争锋玩法。<br>3、直到本赛季最后一天比赛期前，报名公会<font color=#00FF0c>大于50个公会</font>，则本轮跨服争锋<font color=#00FF0c>开启</font>。<br>二、比赛期流程<br>1、每周一至周六为比赛期，比赛期每天进行一轮比赛。<br>2、<font color=#00FF0c>周一至周五均可以报名</font>公会争锋，报名成功会<font color=#00FF0c>加入下一轮比赛</font>的匹配。（0点之后报名，次日才能参赛）<br>3、每天00:00-06:00点会计算公会30级以上玩家数量，人数不足的公会本轮比赛休战；反之，全体大于30级玩家将参与本轮公会战。<br>4、<font color=#00FF0c>每天00:00-22:00为比赛期</font>，符合条件的同段位公会将<font color=#00FF0c>10个公会一个小组两两匹配对战</font>。（最后一个不足10公会的分组会和前一个分组合并）<br>5、轮空的公会将直接获胜晋级，并在当天结算期后获得本轮比赛可得的全部战斗积分。<br>三、比赛规则<br>1、挑战战胜敌方公会玩家，可获得比赛积分，每轮比赛初始比赛积分为0。<br>2、比赛结束后根据比赛积分，判断双方胜负，<font color=#00FF0c>胜利的公会会加上额外比赛积分</font>。<br>a、青铜组胜方额外积分：1500<br>b、白银组胜方额外积分：3000<br>c、铂金组胜方额外积分：4500<br>d、王者组胜方额外积分：7500<br>3、根据22:00的比赛积分，会确定小组排名。<br>a、青铜组：1-6晋级，其余保级。<br>b、白银组：1-5晋级，6-9保级，其余降级。<br>c、铂金组：1-4晋级，5-8保级，其余降级。<br>d、王者组：进入王者组后，不会再降级。<br>4、<font color=#00FF0c>赛季累计积分</font>：赛季开始后每轮比赛获得的积分将累计，作为最后王者组排名依据。<br>四、挑战规则<br>1、每名玩家每天可以有3次出手机会，每个对手有3次防守次数。<br>2、每次挑战无论胜负，均可以获得1次翻牌奖励。<br>五、奖励设定<br>1、公会在<font color=#00FF0c>本赛季每提升一个段位均可以开启对应段位的宝箱</font>，段位宝箱数量为当前公会晋级时的公会人数上限。<br>2、相同段位的宝箱每人每赛季最多领取1次，更换公会无法重复获取。<br>3、每个赛季<font color=#00FF0c>周六23:00发放赛季排名奖励</font>，此时处于对应公会的玩家均可获得奖励。",
    TS22: "魔镜转换规则介绍<br>1、魔镜转换可以将10（或11）星英雄转换为同种族其他英雄。<br>2、选择10（或11）星后放入一定数量相同5星英雄，并消耗1000（11星需要1500）永恒置换精华，即可将对应10（或11）星英雄置换为目标英雄。<br>3、作为材料的5星英雄，会返还所有培养材料。（融魂培养材料除英雄经验外全部返还）<br>4、作为结果的10（或11）星英雄会继承原来英雄除开融魂的所有属性。（融魂培养材料除英雄经验外全部返还）",
    TS24: "一、基础说明：<br>1、英雄11星可以激活1个雕文插槽，通过参加巅峰王者可以获得雕文。<br>2、雕文分为绿、蓝、紫、橙、红5个品质，每个品质又分为攻击型、生命型和平衡型。<br>3、同个英雄不可穿戴相同类型的雕文。<br>二、雕文基础属性：<br>1、雕文根据其品质会在生成的时候，在一定区间随机基础属性，越高品质的雕文基础属性越高。<br>2、攻击型和生命型雕文分别偏向攻击属性和生命属性的加成，平衡性则两者均有。<br>3、通过升级可以百分比提升雕文基础属性加成，所有升级带来的百分比相同。<br>4、雕文被精炼、吞噬后会返还所有雕文升级消耗的雕文精华。<br>三、雕文附加属性：<br>1、雕文生成时会随机生成附加属性，越高品质的雕文附加属性条目越多。<br>2、通过洗练可以重新随机更换雕文的附加属性。<br>3、通过锁定功能可以锁定属性后进行洗练。<br>四、雕文附加技能：<br>1、红色品质雕文在生成时会随机生成一条附加技能。<br>2、红色品质雕文通过重铸可以重新随机附加技能。<br>3、同个英雄穿戴多个拥有不同雕文技能的雕文时，每个技能均生效；但是穿戴相同技能的雕文时，相同技能只会生效1条。<br>五、雕文精炼：<br>1、通过锻造坊的精炼功能可以将低品质雕文精炼为高品质雕文，红色品质雕文若精炼成功，则会生成1个新的随机红色品质雕文。<br>2、绿、蓝、紫、橙、红色品质雕文精炼成功率分别为40%、30%、20%、10%、10%，精炼失败雕文会消失并分别返还100、125、150、175、200雕文精华。<br>3、每次精炼雕文无论成功失败均增加1点精炼值，消耗100点精炼值可以兑换一个永恒雕文宝箱。<br>六、雕文吞噬：<br>1、雕文可以吞噬同品质同类型其他雕文的基础属性、附加属性或附加技能的三者或者其一。<br>2、吞噬成功后，被吞噬的基础属性、附加属性、或附加技能会覆盖原有雕文的对应类型（覆盖时无论基础属性或附加属性条目数量，均为直接覆盖某个类型的全部条目）。<br>3、被吞噬的雕文会销毁并返还其升级消耗的所有雕文精华。",
    TS25: "雕文精炼：<br>1、通过精炼功能可以将低品质雕文精炼为高品质雕文，红色品质可精炼为红色品质雕文。<br>2、绿、蓝、紫、橙、红色品质雕文精炼成功率分别为40%、30%、20%、10%、10%，精炼失败分别返还100、125、150、175、200雕文精华。<br>3、每个被精炼雕文无论精炼成功还是失败均增加1点能量，能量到100点必定额外生成1个红色品质雕文。<br>4、精炼时每个雕文精炼成功或失败均是独立计算，和精炼时放入的数量没有关系。",
    TS26: "一.活动简介<br>1.巅峰王者是一个跨服的高级玩家3队挑战竞技玩法，开服一周后开启功能。<br>2.开启后75级以上玩家可参与玩法，全体玩家均可以参与竞猜王者活动。<br>3.玩法主要流程分为<font color=#00FF0c>报名阶段、大乱斗阶段、钻石赛阶段、竞猜王者阶段</font>和<font color=#00FF0c>王者赛阶段</font>；<br>二.报名规则<br>1.每周一00:00-22:00为巅峰王者的报名阶段，届时所有<font color=#00FF0c>等级达到75级及以上</font>的玩家均可报名参与；<br>2.报名成功后可立即获得雕文精华*500；<br>3.若报名期间<font color=#00FF0c>人数大于256名</font>玩家，则本届巅峰王者活动将在周二00:00正式开启；<font color=#00FF0c>人数不足</font>则本期活动无法开启。<br>三.大乱斗介绍<br>1.每周二00:00-22:00为巅峰王者大乱斗比赛期，所有报名的玩家可以参与活动；<br>2.大乱斗一共可以<font color=#00FF0c>进行15场</font>战斗，每场战斗胜利可得10分，失败得2分，如若连胜（1胜除外）可额外获得对应连胜次数的分数；<br>3.大乱斗中积分达到指定条件即可通过邮件<font color=#00FF0c>依次领取乱斗分数包含在内的所有档次奖励</font>；<br>4.大乱斗结束后<font color=#00FF0c>分数排名前256的玩家将晋级钻石赛</font>，积分相同按历史最高战力排序<font color=#00FF0c>（该战力为本期活动挑战大乱斗时最强战力）</font>；<br>5.每周二22:05分所有晋级钻石赛的玩家将陆续收到晋级奖励邮件；<br>四.钻石赛介绍<br>1.晋级钻石赛的256名玩家将随机分配到16个钻石赛小组中，每个小组16名玩家两两随机匹配进行淘汰赛；<br>2.每周三12:00将进行钻石赛分组赛（16进8）的比赛，比赛将进行三轮，<font color=#00FF0c>每隔5分钟一轮战斗，三轮两胜制</font>；<br>3.每周三20:00、周四12:00、周四20:00将进行8进4、半决赛和决赛，并在每周四20:10决出16个钻石组的冠军；<br>4.每周四20:10分将会陆续发放钻石赛奖励（<font color=#00FF0c>钻石赛奖励只能领取达到最高名次奖励</font>），并且各小组的冠军将会入选王者赛；<br>五.竞猜王者介绍<br>1.每周四20:10-周五23:59所有贵族1以上并且等级达到30级以上的玩家都可以到对应界面选择一名钻石赛冠军玩家进行竞猜；<br>2.竞猜分为三挡<br>  ※贵族1以上玩家可购买100钻幸运之星礼包；<br>  ※贵族5以上玩家可购买200钻加油助威礼包；<br>  ※贵族7以上玩家可购买300钻天命王者礼包；<br>  ※购买礼包的同时会进行对应钻石档位的竞猜；<br>3.所有<font color=#00FF0c>购买礼包的金额将累积到竞猜王者奖池中</font><br>  ※竞猜中冠军则享受冠军奖池。（总奖池40%）<br>  ※竞猜中亚军则享受亚军奖池。（总奖池30%）<br>  ※竞猜中四强则享受四强奖池。（总奖池30%）<br>4.若竞猜的目标成为了冠军、亚军、四强，则所有竞猜对的玩家将根据档位平分奖池的奖励。<br>  ※100钻：竞猜正确玩家平分奖池20%<br>  ※200钻：竞猜正确玩家平分奖池30%<br>  ※300钻：竞猜正确玩家平分奖池50%<br>5.王者赛结束后将逐步发放竞猜奖励，若竞猜成功将获得对应平分奖励的钻石<font color=#00FF0c>（最高不超过礼包金额的10倍）</font>，若竞猜失败将获得10000金币；<br>六.王者赛介绍<br>1.周六00:00竞猜结束后，钻石赛各小组的第1名共16人将会随机两两配对，进行<font color=#00FF0c>五轮三胜制</font>的淘汰赛；<br>2.周六12:00、周六20:00、周日12:00、周日20:00将分别进行16进8、8进4、半决赛和决赛；<br>3.周日20:20将会决出最强王者并逐步发放王者赛相关的排名奖励以及竞猜奖励。<br>七.其他功能介绍<br>1.更换阵型：<br>  ※晋级钻石赛的玩家可以进行更换阵型，将当前的阵型保存为后续比赛的阵型。<br>  ※<font color=#00FF0c>（每轮晋级赛开启时间的上下30分钟不可保存阵型）</font><br>2.王者之巅：<br>  ※每期巅峰王者周日20:25更新王者之巅，用于记录巅峰王者历史所有四强玩家。<br>3.自动报名：<br>  ※贵族2以上且等级达到75级以上玩家可以勾选自动报名。<br>  ※勾选后未来每期巅峰王者活动开启报名时（每周一00:00）将自动为你报名活动，并通过邮件发送报名的雕文精华奖励。<br>4.战斗胜利：15回合内优先战胜敌方全部英雄的玩家将获胜；如若平局，则战力较高的玩家获得胜利。<br>八.王者雕塑<br>1.每期巅峰王者32强玩家（钻石赛亚军及以上）玩家将成为本服的守护者，其名称将在未来一周悬挂在王者雕塑之上。<br>2.每个服务器至多一名守护者，若本服存在多个32强玩家，则排名较高者得；若排名相同，则巅峰王者历史战力较高者得。<br>3.服务器全体玩家(包括自己)均可为膜拜本服守护者，膜拜后将立刻获得一次快速探险收益，并未本服守护者提升鲜花值。<br>4.本服守护者可根据收到的鲜花值领取友情印记（每期活动至多可以领取150友情印记）",
    TS27: "一.限时招募<br>1、活动期间通过限时招募会有更高概率招募到新英雄。<br>2、每天都会有一次免费的限时招募机会，不要错过。<br>3、活动期间每次招募都可以获得10点积分，积分达到条件即可开启宝箱获取新英雄。<br>4、每次招募活动结束，服内积分排名较高的玩家可以获得额外排名奖励。",
    TS28: "一.公会任务<br>1.公会任务功能开启后，入会3天以上，且80级以上玩家均可完成公会任务。<br>2.公会成员自身进行3级捐献、完成日常任务等操作，均会计算到公会任务的统计中。<br>3.会长和官员玩家可以提交完成的公会任务，完成后公会将获得对应补给。<br>4.会长和官员消耗补给，开启征讨首领，挑战首领参战成员均可获得奖励。<br>5.每次开启征讨首领至少需要间隔2天（当日开启，至少需要后天才能开启下一轮）。",
    TS29: "一.功能简介<br>1.每天10点开始可以挑战神殿魔王，初始有3次挑战次数，而后12,14,16,18,20点均会恢复1次挑战次数。<br>2.神殿魔王有3位，每天会轮流守卫神殿：<br>--a.火焰魔王：前4回合火焰守卫会守护魔王，4回合后火焰守卫会唤醒火焰魔王，对全体敌人造成100%生命上限伤害。<br>--b.恶魔刺客：恶魔刺客每回合对全体敌人造成生命上限25%的伤害；其2名爪牙每回合会对随机1个敌人造成20%生命上限伤害，并有50%概率眩晕敌人。<br>--c.亡灵领主：亡灵领主每回合对顺位1名敌人造成生命上限100%伤害；其4名爪牙每回合会有50%概率随机冰冻1名敌人。<br>3.魔王躯体：魔王命中+999%，免控+999%（恶魔刺客与亡灵领主的爪牙无该效果）<br>4.魔王受到诅咒，每天会随机受到某个种族或职业的伤害会增加。（种族和职业的溢伤效果可叠加）<br>5.每天根据勇者对魔王造成伤害排名，勇者们可以得到一份奖励。",
    TS30: "一.公会任务<br>1.公会任务功能开启后，入会3天以上，且80级以上玩家均可完成公会任务。<br>2.公会成员自身进行3级捐献、完成日常任务等操作，均会计算到公会任务的统计中。<br>3.会长和官员玩家可以提交完成的公会任务，完成后公会将获得对应补给。<br>4.会长和官员消耗补给，开启征讨首领，挑战首领参战成员均可获得奖励。<br>5.每次开启征讨首领至少需要间隔2天（当日开启，至少需要后天才能开启下一轮）。",
    TS31: "王者雕塑<br>1.每期巅峰王者32强玩家（钻石赛亚军及以上）玩家将成为本服的守护者，其名称将在未来一周悬挂在王者雕塑之上。<br>2.每个服务器至多一名守护者，若本服存在多个32强玩家，则排名较高者得；若排名相同，则巅峰王者历史战力较高者得。<br>3.服务器全体玩家(包括自己)均可为膜拜本服守护者，膜拜后将立刻获得一次快速探险收益，并未本服守护者提升鲜花值。<br>4.本服守护者可根据收到的鲜花值领取友情印记（每期活动至多可以领取150友情印记）",
    lvmax: "等级上限",
    SHENG: "胜",
    atk: "攻击",
    def: "防御",
    hp: "生命",
    yjh: "已激活",
    SQ: "神器",
    speed: "速度",
    atkpro: "攻击",
    defpro: "防御",
    hppro: "生命",
    VIPKT: "VIP{1}可开{2}人团",
    speedpro: "速度",
    jingzhunpro: "命中率",
    gedangpro: "格挡率",
    BKXXQTDWSQ: "不可卸下其它队伍神器",
    baojipro: "暴击率",
    baoshangpro: "暴击伤害",
    skilldpspro: "技能伤害",
    staratkpro: "攻击百分比",
    starhppro: "生命百分比",
    pojiapro: "破防率",
    miankongpro: "免控率",
    undpspro: "伤害减免",
    dpspro: "伤害加成",
    pvpdpspro: "pvp伤害增加",
    pvpundpspro: "pvp伤害减免",
    OPEN_TO_STAR:'距离开始',
    OPEN_TO_END:'距离结束',
    JJC_FREE_NOWORK:'自由竞技场休息时间，请24点之后再来',
    JJC_GUANJUN_NOWORK:'冠军试炼未开启',
    JIANDAN: "简单",
    PUTONG: "普通",
    KUNNAN: "困难",
    DIYU: "地狱",
    EMENG: "噩梦",
    JUEWANG: "绝望",
    JJ1: "军事区预览",
    JJ2: "瘟疫区预览",
    JJ3: "会议区预览",
    HFBJS: "{1}后副本结束",
    JF: "积分",
    SH: "伤害",
    DJG: "第 {1} 关",
    GUANQIA:'关卡',
    WCGS: "完成个数",
    JLJS: "距离结束:",
    CENGSHU: "层数",
    DJCS: "点金次数",
    HDJS: "活动结束",
    YZTG: "远征通关",
    XSCS: "悬赏次数",
    KSTX: "探险次数",
    WDCS: "我的次数",
    WDSC: "我的胜场",
    SZTJBZ: "任务开启条件未满足",
    SZSLBZ: "上阵英雄数量不足",
    WKSCYJ: "无可删除邮件",
    CGSCSYWJLYJ: "成功删除所有无奖励邮件",
    WKLQJLYJ: "无可领取奖励邮件",
    BBKJ: "邮件数量: {1}/50",
    SJR: "收件人:",
    QTGHCY: "公会成员",
    DJBJ: "请输入文字",
    GH: "<font color=#9a4cc6>(公会)</font>",
    WJ: "<font color=#32a2c7>(玩家)</font>",
    HZ: "<font color=#9a4cc6>(会长)</font>",
    GHTZ: "公会通知",
    HUIZHANG: "会长：",
    GENGHUAN: "更换",
    SJWZZWDS: "赛季荣耀王者暂未诞生",
    GHBXSY: "宝箱剩余：<font color=#30ff01>{1}个</font>",
    SLYJ: "私聊邮件",
    BTZDBZ: "标题最多输入8字",
    BTBNWK: "标题不能为空",
    NRBNWK: "内容不能为空",
    DJT:"第{1}天免费领",
    LJJT: "累计<font color=#22b529>{1}</font>天",
    BXW: "宝箱位",
    BXYGQ: "宝箱已过期",
    YQW: "已抢完",
    YCY: "已充：{1}元",
    PMJL:'排名奖励',
    SJJL:'赛季奖励',
    MY_RANK:'我的排名：',
    DXT: "第<font color=#ff8400> {1} </font>天",
    MTJL: "每天21点发放排名奖励",
    SJJL_RANK_INFO:'每周日，根据结算时排名发放奖励',
    JJC_FIGHT_OVER:'新赛季暂未开启',
    JJC_FSBD_TIP:'请设置防守部队',
    JJC_FSBD_GJ_TIP:'每只队伍至少一位英雄',
    PLEASE_OPEN_CARD:'请选择一张卡牌',
    XS: "小时",
    QR: "确认",
    SQLBWK: "申请列表为空",
    DJBZ: "等级不足",
    GZXKGM: "贵族{1}玩家可购买",
    DQGNXJKQ: "当前功能{1}级开启",
    XYLVKQ: "需要{1}级开启",
    HTW: "{1}后逃亡",
    HJL: "{1}后魔王降临",
    SWZMJ: "守望者秘境",
    MRSL: "每日试炼",
    WYZB: "外域争霸",
    SZJYZ: "十字军远征",
    MWXX: "魔王信息",
    MWRD: "魔王弱点",
    JJC: "竞技场",
    SJS: "召唤之书",
    XYC: "魔法转盘",
    FST: "巨龙神殿",
    XSRW: "悬赏任务",
    GM: "购买",
    WC: "完成",
    SYCG: "使用成功",
    XJKQ: "{1}级开启",
    WCTUZL: "完成屠龙之路激活神器",
    FXZ: "发现者：",
    GYXCYFSZR: "该英雄处于防守阵容中",
    GYXBSD: "该英雄被锁定",
    QXZXYFZDYX: "请先选择需要置换的10星英雄",
    TGGQ: "通关{1}/{2}关",
    XYWJCRDL: "次日登录赠送",
    JHZZYK: "激活至尊月卡",
    JLCYM: "精炼槽已满",
    ZWKFRDW: "暂无可放入雕文",
    YJFRCG: "一键放入成功",
    SLYDSX: "数量已达上限",
    CACKDWXQ: "长按查看雕文详情",
    DJSX: "等级上限：",
    XUELIANG: "血       量：",
    GONGJI: "攻       击：",
    ZANLI: "战       力：",

    ZJSL: "你太强了，敌人落荒而逃！",
    CJXJKQ: "成就任务{1}级开启",
    JSSJ: "结束时间",
    KSSJ: "开始时间",
    SQCD: "神器穿戴",
    JH: "激活",
    XX: "卸下",
    JJC_FSBD_GJ_TIP:'请放入需要出战的英雄',
    GMCSBZ: "购买次数不足",
    MXTQ: "<font color=#8d1099>【冒险特权】</font><br>每天首次钻石、刷新券刷新必出紫色任务<br>",
    YXTQ: "<font color=#e85911>【英雄特权】</font><br>每天第3次钻石、刷新券刷新必出橙色任务<br>",
    YJH_1: "<font color=#fdd464>(已激活)</font>",
    WJHMX: "<font color=#63584a>(未激活: 购买冒险礼包激活)</font>",
    WJHYX: "<font color=#63584a>(未激活: 购买英雄礼包激活)</font>",
    YZH:'已转换',
    DUIHUAN:'兑换',
    WU:'暂无',
    QW: "前往",
    BTN_GOUMAI:'购买',
    LBGQ:'礼包已过期，无法购买',
    NEED_NUM:'请输出数量',
    FIGHT_JS_TIP:'贵族{1}或者等级达到{2}级方可开启{3}倍速',
    FIGHT_TG: "{1}级或贵族{2}可跳过战斗",
    world_opiton:'屏蔽世界聊天',
    guild_opiton:'屏蔽公会聊天',
    recruit_opiton:'屏蔽招募信息',
    hide_vip: "隐藏贵族徽章",
    kuafu: "屏蔽跨服信息",
    LZWY: "当前玩家来自外域，无法查看",
    HSXF: "还剩{1}份",
    GHJXYC: "每天只能捐献一次，是否确定捐献本档？",
    FS: "发送",
    YYSL: "拥有数量：{1}",
    XZFXPD:'选择你要分享的频道',
    LT_SHOW_ITEM:'{1} <font color=#804326>LV:{2}</font><font node=1></font><font color=#c80000>{3}</font>',
    SXXH: "<font node=1></font> <font color={1}>{2}</font>",
    XG: "限购{1}",
    systemXX:'[系统消息]',
    NOTID:'此ID不存在',
    applyChengong:'申请成功',
    shieldsuccess:'移除成功',
    sendsuccess:'赠送成功',
    SDCG: "锁定成功",
    JSCG: "取消锁定成功",
    jifen:'得分：',
    dps:'伤害：',
    gitf:'领取成功',
    JIFENPHB:'积分排行',
    DPSPHB:'伤害排行',
    DIREN:'敌人',
    DAOJU:'道具',
    jifenphb:'积分',
    gonghuipindao:'20级以上方可发送',
    jifenjiangli:'积分奖励',
    HDZS:'可获得{1}',
    CHONGZHI_ZCZ:'<font color=#ececd3>再充值</font><font size=24>{1}</font><font color=#ececd3>元即可成为</font>',
    price:'<font node=1></font>{1}',
    sale:'折',
    baoji: "暴击",
    XJWFFJ: "当前英雄星级过高，无法分解",
    gedang: "格挡",
    HYBCWX: "还有<font color=#30ff01>{1}</font>次必出五星",
    BCWX: "此次必出五星",


    PHB_GQ: "关卡",
    PHB_JF: "积分",
    PHB_ZL: "战力",
    PHB_CS: "层数",
    PHB_DJ: "等级",
    PHB_TJ: "激活",
    PHB_CJ: "成就",

    WDDDW: "公会未达到对应段位",
    GHZ_SJ: "S{1}赛季",
    GHZ_YBM1: "已报名",
    GHZ_WBM: "未报名",
    GHZ_YBM: "第{1}轮{2}赛匹配中",
    GHZ_BMGH: "报名公会：{1}",
    GHZ_TJ: "等待会长、官员报名中",
    GHZ_BMCG: "报名S{1}赛季成功",
    GHZ_BMSB: "只有会长、官员可报名公会争锋",
    GHZ_BMSJ: "报名S{1}赛季",
    GHZ_DW1: "青铜",
    GHZ_DW2: "白银",
    GHZ_DW3: "铂金",
    GHZ_DW4: "王者",
    GHZ_SC: "第{1}/{2}轮 {3}赛",
    GHZ_PPSB: "匹配失败，本轮匹配时公会30级玩家少于10人",
    GHZ_XZ: "休战：本轮匹配人数不足",
    GHZ_DDXZ: "第{1}轮{2}赛休战中",
    GHZ_SQJSZ: "比赛结算中.....",
    GHZ_SLSQPM: "上轮赛区排名",
    ZU: "组",
    GHZ_SLJS: "第{1}轮{2}赛结束",
    GHZ_JSQ: "结算期",
    GHZ_DDPP: "第{1}轮{2}赛匹配中",
    GHZ_BLJF: "本轮积分+",
    GHZ_LKJF: "轮空积分+",
    GHZ_WZRANK: "王者{1}名",
    GHZ_CRBM: "次日可报名下轮比赛",
    GHZ_LK: "本轮轮空",
    GHZ_GXLK: "恭喜轮空直接晋级{1}组",
    GHZ_PPZ: "第{1}/{2}轮{3}赛匹配中",
    GHZ_SJJS: "赛季结束",
    SJJG: "S{1} 赛季结果",
    GHZ_ZWZDXX: "暂无战斗信息",
    XLDJS: "下轮比赛: ",


    ZBSLBZ: "装备数量不足",
    DJM: "第{1}名",
    ERR_NO: "本轮比赛匹配时未达成参与条件",
    ERR_LV: "30级以上玩家方可参与",
    ERR_NUM: "本轮比赛挑战次数不足",
    ERR_HEALTH: "当前玩家脸都被打肿了，换个挑战吧！",
    GHSJDWJL: "公会赛季段位奖励",
    mygh: "公会成员<font color=#30ff01>{1}</font>挑战了敌方公会成员<font color=#c80000>{2}</font>，对其造成<font color=#30ff01>{3}</font>点伤害。",
    rival: "敌方公会成员<font color=#c80000>{1}</font>挑战了我方公会成员<font color=#30ff01>{2}</font>，对其造成<font color=#c80000>{3}</font>点伤害。",
    mygh_win: "并成功获取{1}积分",
    rival_win: "我方成员惜败！",
    GHZ_PMJL: "组{1}名公会成员奖励",
    GHZ_YH: "组{1}公会成员奖励",
    GHZ_QB: "组{1}名以后公会成员奖励",
    DI: "第",
    WRWZ: "未上榜",
    JJ_1: "晋级区",
    JJ_0: "保级区",
    "JJ_-1": "降级区",
    ZPM: "组排名",

    WCRWGS: "完成任务个数： ",


    GZJSCSJS: "贵族3解锁传说祭祀",
    todaycs:'今日剩余{1}次',
    HD_timeDown:'剩余:{1}',
    SHENGYU:'剩余:',
    GZZS:'贵族{1}专属',
    GZXGM:'贵族{1}以上玩家方可购买',
    MRSG_PAYNUM:'每日限购{1}次',
    MRXG: "福利礼包",
    GONGHUI:'公会',
    BIANHAO:'编号',
    UI_TITLE_WJXX:'玩家信息',
    NEXT_treasure:'下次搜寻时间:{1}',
    WANJIA: "主角",
    XuanXing:'功能',
    BangZhu:'公告',
    FanKui:'反馈',
    UUID:'<font color=#804326>ID:</font>{1}',
    ToDaySx:'已达今日购买上限',
    czlb_djs:'{1}天',
    czlb_djs1: "{1}小时",
    czlb_djs2: "{1}分钟",
    heartError_00 :'领取并赠送成功！',
    heartError_01 :'当前领取已达上限！',
    heartError_02 :'赠送成功，当前没有友情印记可以领取！',
    heartError_10 :'赠送已经达到上限，领取友情印记成功！',
    heartError_11 :'领取和赠送友情印记都已经达到上限！',
    heartError_12 :'赠送已经达到上限，当前没有可以领取！',
    heartError_13 :'没有可以赠送的好友',
    heartError_20 : '没有可以赠送的好友，领取友情印记成功！',
    heartError_21 : '当前领取已达上限！',
    heartError_22: '没有可以赠送的好友，没有可以领取！',
    tanxian_gj_error:'没有可领取的挂机奖励',
    gonghui_juanxian:'<font node=1></font>x{1}',
    gonghui_gm:'《{1}》公会诚邀你的加入',
    COLOR0: '白色',
    COLOR1: '绿色',
    COLOR2: '蓝色',
    COLOR3: '紫色',
    COLOR4: '橙色',
    COLOR5: '红色',
    ZSZZ: "属性激活限定: ",
    ZZ1: "亡灵",
    ZZ2: "奥术",
    ZZ3: "邪能",
    ZZ4: "自然",
    ZZ5: "神圣",
    ZZ6: "黑暗",
    QXZSYYX: "请选择使用英雄",
    DQZWSFGM: "当前暂无{1}，是否花费{2}钻石购买",
    SHENQI_XXJ:'属性{1}级',
    SHENQI_bt: "{1}({2}级)",
    SHENQI_JCSX: '<font color=#fbc647>基础属性</font>',
    SHENQI_JBJC:'基础属性',
    SHENQI_ZSJC:'特殊属性 <font color=#be5e30>(专属加成需要装备神器方可生效)</font>',
    SHENQI_JCJC:'<font color=#fbc647>基础属性 （升级属性强化效果）</font>',
    SHENQI_JNJC:'<font color=#fbc647>特殊属性 （升级技能激活效果）</font>',
    SHENQI_atk:'全队攻击+{1}',
    SHENQI_hp:'全队血量+{1}',
    SHENQI_KILLBUFF: '全队{1}+{2}',
    SHENQI_JNDJ: '（技能等级{1}级）',
    SHENQI_KILLBUFF_H: '<font color=#6c6c6c>全队{1}+{2}</font>',
    SHENQI_JNDJ_H: '<font color=#6c6c6c>（技能等级{1}级）</font>',
    SHENQI_JNJC_NAME: '技能加成',
    SHENQI_JNDJ1: '<font color=#22b529>技能{1}：{2}+{3}</font>',
    SHENQI_JNDJ1_H: '<font color=#B2B2B2>技能{1}：{2}+{3}</font>',
    DQGJSY: "当前挂机收益",
    DQGJSC: "挂机时长 {1}",
    SQ_QXWC: "请先完成前一章节所有任务",
    SHENQICHONGZHU:'重铸后神器将回到<font color=#fbc647>初始状态</font>，并返还除开金币外所有资源，是否重铸？',
    SMR: '神秘人',
    SJQM: '随机取名按钮',
    KUAFULTL:'30级且开服第2天开启',
    YWZB_QF:'区服:{1}',
    PHB_MAIN_HZ:'会长:{1}',
    PHB_MAIN_GH:'公会:{1}',
    PHB_MAIN_HZ_1:'会长: {1}',
    PHB_MAIN_GH_1:'公会: {1}',
    PHB_MAIN_JRGH:'未加入公会',
    CZ: "重置",
    FK: "亲爱的勇者大大们:\n" +
        "       为了让你有更好的游戏体验，期望你能将你在游戏中体验到的问题反馈给我们，请通过游戏公告的联系方式联系我们，谢谢！\n" +
        "" +
        "" +
        "",
    VIP_1: "1.拥有专属客服，领取高级定制礼包;",
    VIP_2: "2.优先处账号、充值、游戏体验等问题无需等待；",
    VIP_3: "3.意见、建议专属反馈，直通策划;",
    VIP_4: "4.专属个性化关怀服务;",
    VIP_5: "5.更多专属活动、礼包，敬请期待。",
    KFQQ: "VIP客服QQ：",
    JRLC: "今日累充：<font color=#fff32d>{1}元</font>",
    HDSJ: "活动时间：",
    NIAN: "年",
    YUE: "月",
    RI: "日",
    ZHI: " 至 "
};

var _FIRSTNAME = ["豁达","风度","柔韧","兴奋","激奋","惧怕","怒吼","悲伤","俊美","扁平","朴素","庄重","和谐","坦然","豁达","风度","柔韧","温柔","苗条","可人","内向","青春","伤心","美丽","呆滞","潇洒","高雅","洋气","快乐","激昂","恐惧","震怒","悲痛","恬静","小巧","大方","端庄","友爱","踊跃","潇洒","高雅","洋气","可爱","秀气","妖冶","外向","冷漠","痛苦","帅气","心烦","不凡","情调","海涵","喜悦","激情","胆怯","气愤","悲惨","慈祥","笔直","整洁","安闲","认真","端庄","不凡","情调","海涵","善良","娇美","妖媚","丑陋","冷魅","悲伤","清秀","伤感","雍容","淡泊","儒雅","愉快","敬佩","畏缩","担忧","悲凉","苍白","端庄","时髦","安详","美丽","妩媚","雍容","淡泊","儒雅","无邪","娇媚","妩媚","绝美","邪魅","悲泣","活泼","黯然","轩昂","迷人","淡定","畅快","佩服","发慌","发愁","哀伤","白皙","秀气","摩登","恬静","结实","坚强","轩昂","迷人","淡定","率性","娇艳","冰冷","素雅","甜美","忧伤","温柔","惆怅","爽朗","安然","欢畅","崇拜","心慌","犯愁","哀怨","清秀","秀美","讲究","文雅","爽朗","安然","漂亮","艳丽","忧郁","淡雅","倾城","悲痛","娇小","开心","悠然","宁静","欢喜","钦仰","恐慌","忧伤","忧伤","光滑","巧嘴","笔挺","镇静","悠然","宁静","美丽","清纯","清秀","高贵","倾国","沮丧","高大","从容","随和","欢腾","惊恐","激怒","忧愁","伤感","英俊","朱唇","邋遢","沉着","从容","随和","文雅","单纯","靓丽","优雅","倾世","气馁","狡猾","坦荡","随性","欢快","惊慌","恼火","忧心","瘦削","红润","苍白","俗气","诚挚","坦荡","随性","文静","活泼","害羞","高雅","美女","郁闷","阴险","大方","傲骨","欣喜","惊吓","怒斥","愁闷","憔悴","挺直","红润","憨厚","大方","傲骨","烦躁","胆小","幸运","宽容","大气","恳切","宽容","大气","低沉","勇敢","嬉笑","厚道","王者","潇洒","厚道","王者","消沉","乐观","狂笑","妩媚","羞涩","腼腆","严厉","冷酷","坚毅","傲慢","疲惫","沮丧","失神","诧异","发愣","尴尬","踌躇","悲观","消极","酸涩","落魄","绝望","喜悦","狂喜","尽情","快乐","愉悦","畅快","欣喜","幸福","得意","痛快","满足","欢乐","快活","甜美","微笑","兴奋","自豪","欣慰","高兴","满意","安静","孤僻","外向","羞涩","坚强","守信","陶醉","逸乐","快慰","欢喜","荣幸","尽情","舒畅","愉快","喜哈","愉快"];
var _MIDNAME = ['·'];
var _LASTNAME = ["海柔尔","塞莉亚","温柔","红人","姗姗","浪子","奥斯汀","赫瑟尔","夏洛特","灵魂","小珊","空空","奥斯汀","赫达","绮莉","无情","笑傲","天使","卡卡","白壁德","海伦","克洛怡","潇洒","神圣","咪咪","清景","巴比","海洛伊","克莱儿","无忧","大爱","蜜蜜","晓林","巴比特","胡尔达","克莱拉","繁华","天使","小蜜","庆","巴赫","埃达","克莱曼","柔情","温柔","小秘","阿信","培根","艾尔玛","康斯坦","绝版","灵魂","莫莫","波特","鲍德温","伊莎尔","科拉","寂寞","无情","沫沫","草雉","巴纳德","杰奎琳","卡洛儿","幻想","潇洒","么么","巴神","巴尼","乔","妮莉雅","旋律","无忧","猫猫","笨笨","巴雷特","琼","黛西","优雅","繁华","美子","飞飞","巴雷特","希伯来","黛儿","精彩","柔情","雯雯","浮云","巴里","乔伊","黛娜","辉煌","绝版","小雯","仙人","巴特","乔伊斯","黛芙妮","荣耀","寂寞","晓雯","东东","巴塞洛","朱恩","达莲娜","梦之","幻想","乐乐","天宇","巴利特","卡玛","潼恩","寻梦","旋律","小仙","灰狼","巴顿","凯伦","黛碧","精英","优雅","仙儿","光光","拜耳","凯伊","迪得莉","精彩","格格","阳阳","鲍尔","金百莉","迪丽雅","记忆","辉煌","小倩","冷风","蒲福","吉蒂","丹尼丝","伤心","荣耀","倩倩","竹子","比尔德","克里斯","黛安娜","迷糊","梦之","小茜","牙牙","博福特","罗瑞尔","黛娜","善良","寻梦","小倩","小神","比彻","罗伦","唐娜","安","精英","公主","泡泡","贝克","李","多拉","比利","小诺","战神","贝基","盖尔","多琳","琼斯","记忆","小","使者","比尔博","林赛","多莉丝","卡尔","伤心","多多","小龙","贝尔","洛兰","桃乐斯","查理","迷糊","汐","胖胖","贝拉米","璐易丝","尔莎","嘉利","善良","羊羊","闹闹","贝尔","莉迪亚","伊甸","丘奇","安","鬼鬼","毛毛","贝洛克","玛佩尔","伊迪丝","丹","比利","小鬼","大飞","本","玛德琳","艾德文娜","杜威","琼斯","雪舞","皇帝","迪克特","穆得","艾琳","迪克","卡尔","琪琪","春哥","本杰明","塞尔特","艾琳诺","道尔","查理","温柔","酷酷","贝内特","麦格","伊丽莎","盖伊","嘉利","小姐","圈圈","本森","梅根","埃拉","娜","丘奇","雪舞","麦兜","本瑟姆","玛希","艾尔玛","休","丹","心儿","熊熊","伯克利","玛莉提","爱尔莎","伊凡","杜威","欣儿","夜夜","边沁","纳塔利","艾西","乔","迪克","馨儿","麒麟","贝克莱","诺玛","艾娃","梅","道尔","小静","苍穹","伯纳尔","诺维雅","埃米莉","永恒","盖伊","虹虹","阿萨","伯纳德","奥蒂特","埃玛","娜","傲雪","贝齐","伯纳德","欧尔佳","艾丽卡","休","扶子","贝蒂","伯特","普鲁斯","艾丝特","伊凡","素素","布莱兹","伯莎","普莉斯","尤多拉","乔","雨滴","布鲁克","伯蒂","波比","尤妮斯","梅","夏洛特","伯特伦","罗伯塔","伊捷琳","永恒","诺拉","谢里尔","贝色麦","罗克珊","伊芙","克莱拉","贝丝","鲁思","伊夫林","小夏","德博拉","贝西墨","丝柏凌","梵妮","小嫣","多拉","贝西","斯泰西","费怡","语嫣","伊甸","比顿","丝特勒","弗罗拉","天涯","伊迪丝","白求恩","托比","弗伦丝","阿欣","艾伦","贝齐","厄休拉","弗莉达","青青","费滋","贝蒂","维隆卡","菲蕾卡","大白","弗莉达","比尔","维多利","嘉比拉","小白","盖尔","比利","维基","姬玛","白白","乔治亚","比勒尔","维文","珍妮芙","樱花","吉榭尔","布莱克","雷德姬","梧桐","汉纳","布莱克","桑席","格拉迪","月影","赫达","布卢默","耶达","葛瑞丝","小花","海伦","菲尔德","依耶芙特","谢尔达","小兔","埃达","菲尔","丝塔芙","蘑菇","艾尔玛","布卢尔","关德琳","小丫","希伯来","布劳","汉纳","晨曦","乔伊","布卢姆","哈莉特","如梦","乔伊斯","鲍勃","赫瑟尔","囡囡","朱恩","博比","赫蒂","海棠","卡玛","博斯韦","海伦","婷婷","吉蒂","鲍恩","嘟嘟","罗瑞尔","波义耳","希尔达","兔兔","罗伦","鲍曼","希拉莉","糖糖","盖尔","波伊尔","汉妮","三月","林赛","布拉德","埃达","风铃","洛兰","布雷","艾娜","落落","穆得","英格丽","薇薇安","塞尔特","布里奇","艾琳","罂粟","麦格","布赖特","爱莉丝","妮子","梅根","布罗德","艾尔玛","丹丹","欧尔佳","白朗蒂","伊莎蓓","波比","勃朗特","艾薇","糖果","罗伯塔","布鲁克","杰奎琳","菲菲","鲁思","布朗","婕咪","羽毛","丝柏凌","布朗","珍","萝莉","丝特勒","布朗宁","珍妮特","落雪","托比","勃朗宁","珍尼丝","花飞","厄休拉","布鲁斯","琴","暗香","维隆卡","布鲁诺","姬儿","夏天","维基"];

//注意：这个逻辑后端other.json中也有配置，send_chat中也有判断一次
var CHAT_BLOCK_WORD = "礼|充|值|储|返|利|Q|群|裙|福利|折|6|7|8|9|0|零|一|二|四|五|六|七|八|九|十|壹|贰|叁|伍|陆|柒|捌|玖|①|②|③|④|⑤|⑥|⑦|⑧|⑨|⑴|⑵|⑶|⑷|⑸|⑹|⑺|⑻|⑼|⒈|⒉|⒊|⒋|⒌|⒍|⒎|⒏|⒐|㈠|㈡|㈢|㈣|㈤|㈥|㈦|㈧|㈨";
