#!/usr/bin/python
# coding:utf-8
'''
测试英雄
'''


if __name__ == "__main__":
    import sys
    sys.path.append("..")

import g
from ZBFight import ZBFight

def proc(conn, data):
    """
    英雄演示demo
    :param conn:
    :param data: [hid: str]
    :return: 几个战斗特殊判断，'act': 'toShowRole',每回合开始会弹出这个，标示显示哪几个角色， 'act': 'replace'  标示需要替换英雄了，
    ::

        {'d': {'fightres': {'dpsbyside': [1596, 12026],
                    'fightlog': [{'act': 'toShowRole',
                                  'v': ['role_2', 'role_3', 'role_4']},
                                 {'act': 'turn', 'v': 1},
                                 {'act': 'startAct', 'from': 'role_3'},
                                 {'act': 'atk',
                                  'atkType': 'normalskill',
                                  'extData': {},
                                  'from': 'role_3',
                                  'skillid': '11086002',
                                  'to': {'role_0': {'act': 'hp',
                                                    'at': 'nm',
                                                    'baojidps': 0,
                                                    'bj': False,
                                                    'dps': -4511.0,
                                                    'fromRid': 'role_3',
                                                    'jz': True,
                                                    'nv': 1502.0,
                                                    'r': 'role_0',
                                                    'skillid': '11086002',
                                                    'v': -4511.0}}},
                                 {'act': 'nuqi',
                                  'nv': 100,
                                  'r': 'role_3',
                                  'v': 50},
                                 {'act': 'nuqi',
                                  'nv': 60.0,
                                  'r': 'role_0',
                                  'v': 10.0},
                                 {'act': 'stopAct', 'from': 'role_3'},
                                 {'act': 'startAct', 'from': 'role_2'},
                                 {'act': 'atk',
                                  'atkType': 'normalskill',
                                  'extData': {},
                                  'from': 'role_2',
                                  'skillid': '11076002',
                                  'to': {'role_0': {'act': 'hp',
                                                    'at': 'nm',
                                                    'baojidps': 0,
                                                    'bj': False,
                                                    'dps': -3803.0,
                                                    'fromRid': 'role_2',
                                                    'jz': True,
                                                    'nv': -2301.0,
                                                    'r': 'role_0',
                                                    'skillid': '11076002',
                                                    'v': -3803.0}}},
                                 {'act': 'dead',
                                  'canFuHuo': False,
                                  'to': 'role_0'},
                                 {'act': 'nuqi',
                                  'nv': 100,
                                  'r': 'role_2',
                                  'v': 50},
                                 {'act': 'nuqi',
                                  'nv': 70.0,
                                  'r': 'role_0',
                                  'v': 10.0},
                                 {'act': 'stopAct', 'from': 'role_2'},
                                 {'act': 'startAct', 'from': 'role_1'},
                                 {'act': 'atk',
                                  'atkType': 'normalskill',
                                  'extData': {},
                                  'from': 'role_1',
                                  'skillid': '22012002',
                                  'to': {'role_2': {'act': 'hp',
                                                    'at': 'nm',
                                                    'baojidps': 0,
                                                    'bj': False,
                                                    'dps': -1596.0,
                                                    'fromRid': 'role_1',
                                                    'jz': True,
                                                    'nv': 58320.0,
                                                    'r': 'role_2',
                                                    'skillid': '22012002',
                                                    'v': -1596.0}}},
                                 {'act': 'nuqi',
                                  'nv': 100,
                                  'r': 'role_1',
                                  'v': 50},
                                 {'act': 'nuqi',
                                  'nv': 110.0,
                                  'r': 'role_2',
                                  'v': 10.0},
                                 {'act': 'stopAct', 'from': 'role_1'},
                                 {'act': 'startAct', 'from': 'role_4'},
                                 {'act': 'atk',
                                  'atkType': 'normalskill',
                                  'extData': {},
                                  'from': 'role_4',
                                  'skillid': '13046112',
                                  'to': {'role_1': {'act': 'hp',
                                                    'at': 'nm',
                                                    'baojidps': 0,
                                                    'bj': False,
                                                    'dps': -5723.0,
                                                    'fromRid': 'role_4',
                                                    'jz': True,
                                                    'nv': 290.0,
                                                    'r': 'role_1',
                                                    'skillid': '13046112',
                                                    'v': -5723.0}}},
                                 {'_id': 'buff_0',
                                  'act': 'buff',
                                  'bid': 'gedangdrop',
                                  'bt': 'gedangdrop',
                                  'f': 'role_4',
                                  'r': 3,
                                  't': 'role_1'},
                                 {'act': 'nuqi',
                                  'nv': 100,
                                  'r': 'role_4',
                                  'v': 50},
                                 {'act': 'nuqi',
                                  'nv': 110.0,
                                  'r': 'role_1',
                                  'v': 10.0},
                                 {'act': 'stopAct', 'from': 'role_4'},
                                 {'act': 'toShowRole',
                                  'v': ['role_2', 'role_3', 'role_4']},
                                 {'act': 'turn', 'v': 2},
                                 {'act': 'startAct', 'from': 'role_3'},
                                 {'act': 'atk',
                                  'atkType': 'xpskill',
                                  'extData': {},
                                  'from': 'role_3',
                                  'skillid': '11086012',
                                  'to': {'role_1': {'act': 'hp',
                                                    'at': 'xp',
                                                    'baojidps': 0,
                                                    'bj': False,
                                                    'dps': -9060.0,
                                                    'fromRid': 'role_3',
                                                    'jz': True,
                                                    'nv': -8770.0,
                                                    'r': 'role_1',
                                                    'skillid': '11086012',
                                                    'v': -9060.0}}},
                                 {'act': 'dead',
                                  'canFuHuo': False,
                                  'to': 'role_1'},
                                 {'_id': 'buff_1',
                                  'act': 'buff',
                                  'bid': 'atkdrop',
                                  'bt': 'atkdrop',
                                  'f': 'role_3',
                                  'r': 2,
                                  't': 'role_1'},
                                 {'act': 'nuqi',
                                  'nv': 0,
                                  'r': 'role_3',
                                  'v': -100},
                                 {'act': 'nuqi',
                                  'nv': 120.0,
                                  'r': 'role_1',
                                  'v': 10.0},
                                 {'act': 'stopAct', 'from': 'role_3'},
                                 {'act': 'fightres', 'v': 1}],
                    'fightres': {'role_0': {'atk': 2250,
                                            'atkpro': 1000,
                                            'baojipro': 0,
                                            'baoshangpro': 0,
                                            'bd1skill': ('22012111',),
                                            'bd2skill': (),
                                            'bd3skill': (),
                                            'curepro': 0,
                                            'dead': True,
                                            'def': 578,
                                            'defpro': 1000,
                                            'dpspro': 0,
                                            'enlargepro': 1,
                                            'gedangpro': 25,
                                            'head': '22012',
                                            'hid': '22012',
                                            'hp': -2301.0,
                                            'hppro': 1000,
                                            'isBack': True,
                                            'isFront': True,
                                            'jianshangpro': 0,
                                            'jingzhunpro': 0,
                                            'job': 2,
                                            'lv': 100,
                                            'maxhp': 6013,
                                            'maxnuqi': 100,
                                            'miankongpro': 0,
                                            'normalskill': '22012002',
                                            'nuqi': 70.0,
                                            'pojiapro': 0,
                                            'pos': 4,
                                            'pvpdpspro': 0,
                                            'pvpundpspro': 0,
                                            'ready': True,
                                            'rid': 'role_0',
                                            'shenqidpspro': 0,
                                            'side': 0,
                                            'skill': ['22012111'],
                                            'skilldpspro': 0,
                                            'speed': 487,
                                            'speedpro': 1000,
                                            'star': 5,
                                            'test': 1,
                                            'unbaojipro': 0,
                                            'undercurepro': 0,
                                            'undotdpspro': 0,
                                            'undpspro': 0,
                                            'unliuxuepro': 0,
                                            'unzhongdupro': 0,
                                            'unzhuoshaopro': 0,
                                            'xpskill': '22012012',
                                            'zhanli': 3543,
                                            'zhongdudpsdrop': 0,
                                            'zhongdudpspro': 0,
                                            'zhongzu': 2},
                                 'role_1': {'afterXpskillRound': 1,
                                            'atk': 1643,
                                            'atkpro': 1000,
                                            'baojipro': 0,
                                            'baoshangpro': 0,
                                            'bd1skill': ('22012111',),
                                            'bd2skill': (),
                                            'bd3skill': (),
                                            'curepro': 0,
                                            'dead': True,
                                            'def': 578,
                                            'defpro': 1000,
                                            'dpspro': 0,
                                            'enlargepro': 1,
                                            'gedangdrop': 150,
                                            'gedangpro': 25,
                                            'head': '22012',
                                            'hid': '22012',
                                            'hp': -8770.0,
                                            'hppro': 1000,
                                            'isBack': True,
                                            'isFront': True,
                                            'jianshangpro': 0,
                                            'jingzhunpro': 0,
                                            'job': 2,
                                            'lv': 100,
                                            'maxhp': 6013,
                                            'maxnuqi': 100,
                                            'miankongpro': 0,
                                            'normalskill': '22012002',
                                            'nuqi': 120.0,
                                            'pojiapro': 0,
                                            'pos': 5,
                                            'pvpdpspro': 0,
                                            'pvpundpspro': 0,
                                            'ready': True,
                                            'rid': 'role_1',
                                            'shenqidpspro': 0,
                                            'side': 0,
                                            'skill': ['22012111'],
                                            'skilldpspro': 0,
                                            'speed': 487,
                                            'speedpro': 1000,
                                            'star': 5,
                                            'test': 1,
                                            'unbaojipro': 0,
                                            'undercurepro': 0,
                                            'undotdpspro': 0,
                                            'undpspro': 0,
                                            'unliuxuepro': 0,
                                            'unzhongdupro': 0,
                                            'unzhuoshaopro': 0,
                                            'xpskill': '22012012',
                                            'zhanli': 3543,
                                            'zhongdudpsdrop': 0,
                                            'zhongdudpspro': 0,
                                            'zhongzu': 2},
                                 'role_2': {'afterXpskillRound': 1,
                                            'atk': 3811,
                                            'atkpro': 1000,
                                            'baojipro': 0,
                                            'baoshangpro': 0,
                                            'bd1skill': ('11076111',
                                                         '11076121'),
                                            'bd2skill': ('11076214',),
                                            'bd3skill': ('11076314',),
                                            'curepro': 0,
                                            'dead': False,
                                            'def': 633,
                                            'defpro': 1000,
                                            'dpspro': 0,
                                            'enlargepro': 1,
                                            'gedangpro': 0,
                                            'head': '11076',
                                            'hid': '11076',
                                            'hp': 58320.0,
                                            'hppro': 1000,
                                            'isBack': False,
                                            'isFront': True,
                                            'jianshangpro': 0,
                                            'jingzhunpro': 0,
                                            'job': 1,
                                            'lv': 100,
                                            'maxhp': 59916,
                                            'maxnuqi': 100,
                                            'miankongpro': 0,
                                            'normalskill': '11076002',
                                            'nuqi': 110.0,
                                            'pojiapro': 50,
                                            'pos': 1,
                                            'pvpdpspro': 0,
                                            'pvpundpspro': 0,
                                            'ready': True,
                                            'rid': 'role_2',
                                            'shenqidpspro': 0,
                                            'side': 1,
                                            'skill': ['11076111',
                                                      '11076121'],
                                            'skilldpspro': 0,
                                            'speed': 502,
                                            'speedpro': 1000,
                                            'star': 2,
                                            'test': 1,
                                            'unbaojipro': 0,
                                            'undercurepro': 0,
                                            'undotdpspro': 0,
                                            'undpspro': 0,
                                            'unliuxuepro': 0,
                                            'unzhongdupro': 0,
                                            'unzhuoshaopro': 0,
                                            'xpskill': '11076012',
                                            'xpskillindex': 1,
                                            'zhanli': 13048,
                                            'zhongdudpsdrop': 0,
                                            'zhongdudpspro': 0,
                                            'zhongzu': 1},
                                 'role_3': {'afterXpskillRound': 1,
                                            'atk': 4475,
                                            'atkpro': 1000,
                                            'baojipro': 0,
                                            'baoshangpro': 0,
                                            'bd1skill': ('11086111',
                                                         '11086121'),
                                            'bd2skill': ('11086214',
                                                         '11086224'),
                                            'bd3skill': ('11086314',),
                                            'curepro': 0,
                                            'dead': False,
                                            'def': 665,
                                            'defpro': 1000,
                                            'dpspro': 0,
                                            'enlargepro': 1,
                                            'gedangpro': 0,
                                            'head': '11086',
                                            'hid': '11086',
                                            'hp': 50465,
                                            'hppro': 1000,
                                            'isBack': True,
                                            'isFront': False,
                                            'jianshangpro': 0,
                                            'jingzhunpro': 0,
                                            'job': 1,
                                            'lv': 100,
                                            'maxhp': 50465,
                                            'maxnuqi': 100,
                                            'miankongpro': 0,
                                            'normalskill': '11086002',
                                            'nuqi': 0,
                                            'pojiapro': 50,
                                            'pos': 3,
                                            'pvpdpspro': 0,
                                            'pvpundpspro': 0,
                                            'ready': True,
                                            'rid': 'role_3',
                                            'shenqidpspro': 0,
                                            'side': 1,
                                            'skill': ['11086111',
                                                      '11086121'],
                                            'skilldpspro': 0,
                                            'speed': 505,
                                            'speedpro': 1000,
                                            'star': 2,
                                            'test': 1,
                                            'unbaojipro': 0,
                                            'undercurepro': 0,
                                            'undotdpspro': 0,
                                            'undpspro': 0,
                                            'unliuxuepro': 0,
                                            'unzhongdupro': 0,
                                            'unzhuoshaopro': 0,
                                            'xpskill': '11086012',
                                            'xpskillindex': 1,
                                            'zhanli': 12526,
                                            'zhongdudpsdrop': 0,
                                            'zhongdudpspro': 0,
                                            'zhongzu': 1},
                                 'role_4': {'afterXpskillRound': 1,
                                            'atk': 6097,
                                            'atkpro': 1000,
                                            'baojipro': 0,
                                            'baoshangpro': 0,
                                            'bd1skill': ('13046114',),
                                            'bd2skill': ('13046211',
                                                         '13046221'),
                                            'bd3skill': ('13046314',),
                                            'curepro': 0,
                                            'dead': False,
                                            'def': 600,
                                            'defpro': 1000,
                                            'dpspro': 0,
                                            'enlargepro': 1,
                                            'gedangpro': 0,
                                            'head': '13046',
                                            'hid': '13046',
                                            'hp': 38056,
                                            'hppro': 1000,
                                            'isBack': True,
                                            'isFront': False,
                                            'jianshangpro': 0,
                                            'jingzhunpro': 0,
                                            'job': 3,
                                            'lv': 100,
                                            'maxhp': 38056,
                                            'maxnuqi': 100,
                                            'miankongpro': 0,
                                            'normalskill': '13046002',
                                            'nuqi': 100,
                                            'pojiapro': 50,
                                            'pos': 6,
                                            'pvpdpspro': 0,
                                            'pvpundpspro': 0,
                                            'ready': True,
                                            'rid': 'role_4',
                                            'shenqidpspro': 0,
                                            'side': 1,
                                            'skill': ['13046114'],
                                            'skilldpspro': 0,
                                            'speed': 470,
                                            'speedpro': 1000,
                                            'star': 2,
                                            'test': 1,
                                            'unbaojipro': 0,
                                            'undercurepro': 0,
                                            'undotdpspro': 0,
                                            'undpspro': 0,
                                            'unliuxuepro': 0,
                                            'unzhongdupro': 0,
                                            'unzhuoshaopro': 0,
                                            'xpskill': '13046012',
                                            'xpskillindex': 1,
                                            'zhanli': 11353,
                                            'zhongdudpsdrop': 0,
                                            'zhongdudpspro': 0,
                                            'zhongzu': 1}},
                    'headdata': [{'head': '22012',
                                  'lv': 100,
                                  'name': '\xe8\x8c\x85\xe9\x81\x93\xe5\xa3\xab'},
                                 {'head': '11076',
                                  'lv': 100,
                                  'name': '\xe9\xa9\xac\xe8\x85\xbe'}],
                    'roles': {'role_0': {'atk': 2250,
                                         'atkpro': 1000,
                                         'baojipro': 0,
                                         'baoshangpro': 0,
                                         'bd1skill': ('22012111',),
                                         'bd2skill': (),
                                         'bd3skill': (),
                                         'curepro': 0,
                                         'dead': False,
                                         'def': 578,
                                         'defpro': 1000,
                                         'dpspro': 0,
                                         'enlargepro': 1,
                                         'gedangpro': 25,
                                         'head': '22012',
                                         'hid': '22012',
                                         'hp': 6013,
                                         'hppro': 1000,
                                         'isBack': True,
                                         'isFront': True,
                                         'jianshangpro': 0,
                                         'jingzhunpro': 0,
                                         'job': 2,
                                         'lv': 100,
                                         'maxhp': 6013,
                                         'maxnuqi': 100,
                                         'miankongpro': 0,
                                         'normalskill': '22012002',
                                         'nuqi': 50,
                                         'pojiapro': 0,
                                         'pos': 4,
                                         'pvpdpspro': 0,
                                         'pvpundpspro': 0,
                                         'ready': True,
                                         'rid': 'role_0',
                                         'shenqidpspro': 0,
                                         'side': 0,
                                         'skill': ['22012111'],
                                         'skilldpspro': 0,
                                         'speed': 487,
                                         'speedpro': 1000,
                                         'star': 5,
                                         'test': 1,
                                         'unbaojipro': 0,
                                         'undercurepro': 0,
                                         'undotdpspro': 0,
                                         'undpspro': 0,
                                         'unliuxuepro': 0,
                                         'unzhongdupro': 0,
                                         'unzhuoshaopro': 0,
                                         'xpskill': '22012012',
                                         'zhanli': 3543,
                                         'zhongdudpsdrop': 0,
                                         'zhongdudpspro': 0,
                                         'zhongzu': 2},
                              'role_1': {'atk': 2250,
                                         'atkpro': 1000,
                                         'baojipro': 0,
                                         'baoshangpro': 0,
                                         'bd1skill': ('22012111',),
                                         'bd2skill': (),
                                         'bd3skill': (),
                                         'curepro': 0,
                                         'dead': False,
                                         'def': 578,
                                         'defpro': 1000,
                                         'dpspro': 0,
                                         'enlargepro': 1,
                                         'gedangpro': 25,
                                         'head': '22012',
                                         'hid': '22012',
                                         'hp': 6013,
                                         'hppro': 1000,
                                         'isBack': True,
                                         'isFront': True,
                                         'jianshangpro': 0,
                                         'jingzhunpro': 0,
                                         'job': 2,
                                         'lv': 100,
                                         'maxhp': 6013,
                                         'maxnuqi': 100,
                                         'miankongpro': 0,
                                         'normalskill': '22012002',
                                         'nuqi': 50,
                                         'pojiapro': 0,
                                         'pos': 5,
                                         'pvpdpspro': 0,
                                         'pvpundpspro': 0,
                                         'ready': True,
                                         'rid': 'role_1',
                                         'shenqidpspro': 0,
                                         'side': 0,
                                         'skill': ['22012111'],
                                         'skilldpspro': 0,
                                         'speed': 487,
                                         'speedpro': 1000,
                                         'star': 5,
                                         'test': 1,
                                         'unbaojipro': 0,
                                         'undercurepro': 0,
                                         'undotdpspro': 0,
                                         'undpspro': 0,
                                         'unliuxuepro': 0,
                                         'unzhongdupro': 0,
                                         'unzhuoshaopro': 0,
                                         'xpskill': '22012012',
                                         'zhanli': 3543,
                                         'zhongdudpsdrop': 0,
                                         'zhongdudpspro': 0,
                                         'zhongzu': 2},
                              'role_2': {'atk': 3811,
                                         'atkpro': 1000,
                                         'baojipro': 0,
                                         'baoshangpro': 0,
                                         'bd1skill': ('11076111',
                                                      '11076121'),
                                         'bd2skill': ('11076214',),
                                         'bd3skill': ('11076314',),
                                         'curepro': 0,
                                         'dead': False,
                                         'def': 633,
                                         'defpro': 1000,
                                         'dpspro': 0,
                                         'enlargepro': 1,
                                         'gedangpro': 0,
                                         'head': '11076',
                                         'hid': '11076',
                                         'hp': 59916,
                                         'hppro': 1000,
                                         'isBack': False,
                                         'isFront': True,
                                         'jianshangpro': 0,
                                         'jingzhunpro': 0,
                                         'job': 1,
                                         'lv': 100,
                                         'maxhp': 59916,
                                         'maxnuqi': 100,
                                         'miankongpro': 0,
                                         'normalskill': '11076002',
                                         'nuqi': 50,
                                         'pojiapro': 50,
                                         'pos': 1,
                                         'pvpdpspro': 0,
                                         'pvpundpspro': 0,
                                         'ready': True,
                                         'rid': 'role_2',
                                         'shenqidpspro': 0,
                                         'side': 1,
                                         'skill': ['11076111', '11076121'],
                                         'skilldpspro': 0,
                                         'speed': 502,
                                         'speedpro': 1000,
                                         'star': 2,
                                         'test': 1,
                                         'unbaojipro': 0,
                                         'undercurepro': 0,
                                         'undotdpspro': 0,
                                         'undpspro': 0,
                                         'unliuxuepro': 0,
                                         'unzhongdupro': 0,
                                         'unzhuoshaopro': 0,
                                         'xpskill': '11076012',
                                         'zhanli': 13048,
                                         'zhongdudpsdrop': 0,
                                         'zhongdudpspro': 0,
                                         'zhongzu': 1},
                              'role_3': {'atk': 4475,
                                         'atkpro': 1000,
                                         'baojipro': 0,
                                         'baoshangpro': 0,
                                         'bd1skill': ('11086111',
                                                      '11086121'),
                                         'bd2skill': ('11086214',
                                                      '11086224'),
                                         'bd3skill': ('11086314',),
                                         'curepro': 0,
                                         'dead': False,
                                         'def': 665,
                                         'defpro': 1000,
                                         'dpspro': 0,
                                         'enlargepro': 1,
                                         'gedangpro': 0,
                                         'head': '11086',
                                         'hid': '11086',
                                         'hp': 50465,
                                         'hppro': 1000,
                                         'isBack': True,
                                         'isFront': False,
                                         'jianshangpro': 0,
                                         'jingzhunpro': 0,
                                         'job': 1,
                                         'lv': 100,
                                         'maxhp': 50465,
                                         'maxnuqi': 100,
                                         'miankongpro': 0,
                                         'normalskill': '11086002',
                                         'nuqi': 50,
                                         'pojiapro': 50,
                                         'pos': 3,
                                         'pvpdpspro': 0,
                                         'pvpundpspro': 0,
                                         'ready': True,
                                         'rid': 'role_3',
                                         'shenqidpspro': 0,
                                         'side': 1,
                                         'skill': ['11086111', '11086121'],
                                         'skilldpspro': 0,
                                         'speed': 505,
                                         'speedpro': 1000,
                                         'star': 2,
                                         'test': 1,
                                         'unbaojipro': 0,
                                         'undercurepro': 0,
                                         'undotdpspro': 0,
                                         'undpspro': 0,
                                         'unliuxuepro': 0,
                                         'unzhongdupro': 0,
                                         'unzhuoshaopro': 0,
                                         'xpskill': '11086012',
                                         'zhanli': 12526,
                                         'zhongdudpsdrop': 0,
                                         'zhongdudpspro': 0,
                                         'zhongzu': 1},
                              'role_4': {'atk': 6097,
                                         'atkpro': 1000,
                                         'baojipro': 0,
                                         'baoshangpro': 0,
                                         'bd1skill': ('13046114',),
                                         'bd2skill': ('13046211',
                                                      '13046221'),
                                         'bd3skill': ('13046314',),
                                         'curepro': 0,
                                         'dead': False,
                                         'def': 600,
                                         'defpro': 1000,
                                         'dpspro': 0,
                                         'enlargepro': 1,
                                         'gedangpro': 0,
                                         'head': '13046',
                                         'hid': '13046',
                                         'hp': 38056,
                                         'hppro': 1000,
                                         'isBack': True,
                                         'isFront': False,
                                         'jianshangpro': 0,
                                         'jingzhunpro': 0,
                                         'job': 3,
                                         'lv': 100,
                                         'maxhp': 38056,
                                         'maxnuqi': 100,
                                         'miankongpro': 0,
                                         'normalskill': '13046002',
                                         'nuqi': 50,
                                         'pojiapro': 50,
                                         'pos': 6,
                                         'pvpdpspro': 0,
                                         'pvpundpspro': 0,
                                         'ready': True,
                                         'rid': 'role_4',
                                         'shenqidpspro': 0,
                                         'side': 1,
                                         'skill': ['13046114'],
                                         'skilldpspro': 0,
                                         'speed': 470,
                                         'speedpro': 1000,
                                         'star': 2,
                                         'test': 1,
                                         'unbaojipro': 0,
                                         'undercurepro': 0,
                                         'undotdpspro': 0,
                                         'undpspro': 0,
                                         'unliuxuepro': 0,
                                         'unzhongdupro': 0,
                                         'unzhuoshaopro': 0,
                                         'xpskill': '13046012',
                                         'zhanli': 11353,
                                         'zhongdudpsdrop': 0,
                                         'zhongdudpspro': 0,
                                         'zhongzu': 1}},
                    'signdata': {'role_0': {'addhp': 0, 'dps': 0},
                                 'role_1': {'addhp': 0, 'dps': 1596},
                                 'role_2': {'addhp': 0, 'dps': 1502},
                                 'role_3': {'addhp': 0, 'dps': 4801},
                                 'role_4': {'addhp': 0, 'dps': 5723}},
                    'winside': 1,
                    'zhenfa': [{'3': 0}, {'2': 0}]}},
            's': 1}


    """
    _res = doproc(conn, data)
    conn.response(_res)
    conn.send()

def _checkCond(uid, data):
    _chkData = {}
    _hid = str(data[0])
    # 获取plid
    _con = g.GC["hero"][_hid]
    _plid = _con["pinglunid"]
    # 获取当前plid品质最高的英雄id
    _plCon = g.GC["pre_hero_pinglun"][_plid]
    _hidlist = [int(hid) for hid in _plCon]
    _hid = max(_hidlist)

    # 当前英雄的hid
    _chkData['hid'] = _hid
    # 英雄的资质
    _chkData["zizhi"] = _con["zizhi"]
    # 判断是前排还是后排
    _chkData["demotype"] = _con["demotype"]
    return _chkData

@g.apiCheckLogin
def doproc(conn, data):
    _res = {"s": 1}
    uid = conn.uid
    _chkData = _checkCond(uid, data)
    if 's' in _chkData:
        return _chkData

    _hid = _chkData['hid']
    # 获取战斗数据
    _npctype = g.GC["testhero"]["npctype"][_chkData["demotype"]]
    # 根据资质获取主英雄的npc属性
    _mainNpcData = dict(g.GC["testhero"]["heroconfig"][_chkData["zizhi"]])
    _mainNpcData["pos"] = _npctype["pos"]
    _mainNpcData["hid"] = _hid
    _mainNpcData["head"] = _hid
    _mainData = g.m.npcfun.fmtNpc(_mainNpcData)
    _mainData["side"] = 0

    # 获取测试英雄的数据
    # 我方战斗信息
    _myFightData = g.m.fightfun.getNpcFightData(_npctype['mynpcid'])
    _myFightInfo = []
    for data in _myFightData["herolist"]:
        data["test"] = 1
        data["side"] = 0
        _myFightInfo.append(data)
    _myFightInfo.append(_mainData)

    # 敌方战斗信息
    _toFightData = g.m.fightfun.getNpcFightData(_npctype['enemynpcid'][0])
    _toFightInfo = []
    for data in _toFightData["herolist"]:
        data["test"] = 1
        _toFightInfo.append(data)

    f = ZBFight('test')
    # 加入预备的npc数据
    _reserveFightData = []
    for i in xrange(1, len(_npctype['enemynpcid'])):
        _data = g.m.fightfun.getNpcFightData(_npctype['enemynpcid'][i])
        _reserveFightData.append(_data["herolist"])
    f.saveReserveRole(_reserveFightData)

    _fightRes = f.initFightByData(_myFightInfo + _toFightInfo).start()
    _winside = _fightRes['winside']
    _fightRes['headdata'] = [_myFightData['headdata'], _toFightData['headdata']]
    # 手动处理战斗数据，不知道为什么dead变成了True
    for role in _fightRes["roles"]:
        _fightRes["roles"][role]["dead"] = False
    _resData = {}
    _resData['fightres'] = _fightRes

    _res['d'] = _resData
    return _res

if __name__ == '__main__':
    from pprint import pprint
    uid = g.buid("ysr1")
    g.debugConn.uid = uid
    pprint (doproc(g.debugConn, data=[45045]))